
    Problem.create([
        { 
content: "エニックスのSFCゲーム「ワンダープロジェクト」で主人公の少年ロボットピーノはギジン何号型？",
result: 0,
sum: 0,
user_id: 1,
select1: "ギジン5984型",
select2: "ギジン4891型",
select3: "ギジン4687型",
select4: "ギジン4649型",
result_id: 4
},
{ 
content: "声優のTARAKOがオープニングテーマの作詞を手がけたTVアニメは?",
result: 0,
sum: 0,
user_id: 1,
select1: "メイプルタウン物語",
select2: "まじかる☆タルるートくん",
select3: "とんがり帽子のメモル",
select4: "新ビックリマン",
result_id: 3
},
{ 
content: "DS用ゲーム「がんばれゴエモン東海道中大江戸天狗り返しの巻」のナレーションを担当している落語家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "三遊亭楽太郎",
select2: "桂歌丸",
select3: "笑福亭鶴光",
select4: "林家正蔵",
result_id: 2
},
{ 
content: "ペラペラなマリオが大活躍する「ペーパーマリオRPG」でマリオを乗せたり敵を飲み込んでくれる仲間といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "ノコタロウ",
select2: "クリスチーヌ",
select3: "チビヨッシー",
select4: "クラウダ",
result_id: 3
},
{ 
content: "廃墟になった屋敷を探索する和風ホラーアクション「零～zero～」の主人公は?",
result: 0,
sum: 0,
user_id: 1,
select1: "雛咲深紅",
select2: "雛咲深桃",
select3: "雛咲深碧",
select4: "雛咲深黄",
result_id: 1
},
{ 
content: "次の「週刊少年ジャンプ」に連載された人気漫画のうち最終回が全ページ巻頭カラーでなかったのは?",
result: 0,
sum: 0,
user_id: 1,
select1: "SLAM DUNK",
select2: "キン肉マン",
select3: "リングにかけろ",
select4: "ドラゴンボール",
result_id: 2
},
{ 
content: "（アスキーより分岐）「マル勝ファミコン」を発行していた出版社は?",
result: 0,
sum: 0,
user_id: 1,
select1: "秋田書店",
select2: "エンターブレイン",
select3: "角川書店",
select4: "ソフトバンク",
result_id: 3
},
{ 
content: "漫画「魔法先生ネギま！」で主人公・ネギが教えている教科は？",
result: 0,
sum: 0,
user_id: 1,
select1: "日本史",
select2: "英語",
select3: "国語",
select4: "体育",
result_id: 2
},
{ 
content: "日本初の漫画学部を設置したことで有名な京都府にある私立大学は?",
result: 0,
sum: 0,
user_id: 1,
select1: "京都教育大学",
select2: "京都産業大学",
select3: "京都学園大学",
select4: "京都精華大学",
result_id: 4
},
{ 
content: "プロ棋士・桐山零を主人公とする羽海野チカの漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "2月のライオン",
select2: "3月のライオン",
select3: "4月のライオン",
select4: "1月のライオン",
result_id: 2
},
{ 
content: "あまりの人気のためマルコス時代のフィリピンで国民を抑圧するために放送禁止にされた日本のロボットアニメは？",
result: 0,
sum: 0,
user_id: 1,
select1: "機動戦士ガンダム",
select2: "超電磁マシーン　ボルテスＶ",
select3: "ＵＦＯロボ　グレンダイザー",
select4: "マジンガーＺ",
result_id: 2
},
{ 
content: "広告代理店の倒産で4話までしか放送されなかったという逸話で知られる、手塚治虫原作のTVアニメは",
result: 0,
sum: 0,
user_id: 1,
select1: "ドン・ドラキュラ",
select2: "青いブリンク",
select3: "ジェッターマルス",
select4: "バンパイヤ",
result_id: 1
},
{ 
content: "アニメ「キテレツ大百科」に登場する勉三さんは何浪のすえに大学に入学した？",
result: 0,
sum: 0,
user_id: 1,
select1: "5浪",
select2: "4浪",
select3: "7浪",
select4: "6浪",
result_id: 4
},
{ 
content: "（味吉陽一より分岐）「素材の魔術師」と呼ばれるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "堺一馬",
select2: "味吉陽一",
select3: "村田源二郎",
select4: "中江兵太",
result_id: 4
},
{ 
content: "漫画「ハイスクール！奇面組」に登場する奇面組のリーダーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "天野邪子",
select2: "似蛭田妖",
select3: "雲童塊",
select4: "一堂零",
result_id: 4
},
{ 
content: "（一堂零より分岐）腕組のリーダーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "似蛭田妖",
select2: "天野邪子",
select3: "雲童塊",
select4: "一堂零",
result_id: 3
},
{ 
content: "漫画「エレメンタルジェレイド」で、空賊団に所属している主人公の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "クー",
select2: "ケー",
select3: "カー",
select4: "キー",
result_id: 1
},
{ 
content: "イギリスで放送されたときクイーンのギタリストブライアン・メイがテーマ曲を担当した日本の特撮番組は？",
result: 0,
sum: 0,
user_id: 1,
select1: "Xボンバー",
select2: "スターウルフ",
select3: "マイティジャック",
select4: "銀河からのメッセージ",
result_id: 1
},
{ 
content: "深沢美潮のファンタジー小説「フォーチュン・クエスト」で主人公のパステルたちに可愛がられるドラゴンの名は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ピロちゃん",
select2: "シロちゃん",
select3: "クロちゃん",
select4: "ペロちゃん",
result_id: 2
},
{ 
content: "高校生の頃にパソコンゲーム「パラディン」を制作したことがある漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "小林尽",
select2: "赤松健",
select3: "橋口たかし",
select4: "久米田康治",
result_id: 2
},
{ 
content: "水島新司の漫画「ドカベン　スーパースターズ編」で山田太郎が入団した球団は？",
result: 0,
sum: 0,
user_id: 1,
select1: "東京スーパースターズ",
select2: "四国アイランドッグス",
select3: "東北楽天ゴールデンイーグルス",
select4: "福岡ソフトバンクホークス",
result_id: 1
},
{ 
content: "2009年秋に発売されるDS用ゲーム「スパロボ学園」のキャラクターデザインを担当したイラストレーターは？",
result: 0,
sum: 0,
user_id: 1,
select1: "うるし原智志",
select2: "西又葵",
select3: "みつみ美里",
select4: "駒都えーじ",
result_id: 4
},
{ 
content: "アニメ「シスタープリンセス」といえば元々何の読者参加企画？",
result: 0,
sum: 0,
user_id: 1,
select1: "コンプティーク",
select2: "メガミマガジン",
select3: "電撃G'smagazine",
select4: "ファンロード",
result_id: 3
},
{ 
content: "（電撃G'smagazineより分岐）「おとぎストーリー天使のしっぽ」といえば元々、何という雑誌の読者参加企画だった？",
result: 0,
sum: 0,
user_id: 1,
select1: "メガミマガジン",
select2: "ファンロード",
select3: "コンプティーク",
select4: "電撃G'smagazine",
result_id: 1
},
{ 
content: "水島新司の野球漫画「ドカベン」が連載されていた漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊少年サンデー",
select2: "週刊少年チャンピオン",
select3: "週刊少年ジャンプ",
select4: "週刊少年マガジン",
result_id: 2
},
{ 
content: "（週刊少年チャンピオンより分岐）「一球さん」が連載されていた漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊少年サンデー",
select2: "週刊少年チャンピオン",
select3: "週刊少年ジャンプ",
select4: "週刊少年マガジン",
result_id: 1
},
{ 
content: "格闘ゲーム「餓狼 MARK OF THE WOLVES」に登場する鳥のマスクをつけたプロレスラーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "グリフォンマスク",
select2: "フェニックスマスク",
select3: "ペガサスマスク",
select4: "ドラゴンマスク",
result_id: 1
},
{ 
content: "ゲーム「鉄拳５」の登場キャラ、クリスティ・モンティロの格闘スタイルといえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "カポエイラ",
select2: "テコンドー",
select3: "マーシャル・アーツ",
select4: "キックボクシング",
result_id: 1
},
{ 
content: "（カポエイラより分岐、鉄拳5で）ブライアン・フューリーの格闘スタイルといえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "テコンドー",
select2: "マーシャル・アーツ",
select3: "キックボクシング",
select4: "カポエイラ",
result_id: 3
},
{ 
content: "食玩やフィギュアでおなじみのメーカー海洋堂の本社があるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "京都",
select2: "静岡",
select3: "大阪",
select4: "広島",
result_id: 3
},
{ 
content: "（大阪より分岐）ボークスの本社があるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "京都",
select2: "静岡",
select3: "大阪",
select4: "広島",
result_id: 1
},
{ 
content: "パナソニックのゲーム機「３DO　REAL」のCMキャラクターだったのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "マッカーサー",
select2: "ノストラダムス",
select3: "アインシュタイン",
select4: "ナポレオン",
result_id: 3
},
{ 
content: "名作ミステリを原作としたDS用ゲーム「さらば愛しき女よ」で主人公フィリップ・マーロウの声を演じたお笑いタレントは？",
result: 0,
sum: 0,
user_id: 1,
select1: "小島よしお",
select2: "有吉弘行",
select3: "山本高広",
select4: "狩野英孝",
result_id: 3
},
{ 
content: "アニメ「機動戦士ガンダム」に登場するララァ・スン専用モビルアーマーといえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "エルメス",
select2: "シャネル",
select3: "グッチ",
select4: "ヴィトン",
result_id: 1
},
{ 
content: "不思議な力「アリス」を持つ生徒を描いた漫画「学園アリス」で主人公・佐倉蜜柑が持つのは何？",
result: 0,
sum: 0,
user_id: 1,
select1: "発明のアリス",
select2: "幻覚のアリス",
select3: "無効化のアリス",
select4: "炎のアリス",
result_id: 3
},
{ 
content: "（無効化のアリスより分岐）蜜柑の親友・今井蛍が持つのはどんなアリス？",
result: 0,
sum: 0,
user_id: 1,
select1: "炎のアリス",
select2: "無効化のアリス",
select3: "発明のアリス",
select4: "幻覚のアリス",
result_id: 3
},
{ 
content: "2009年にアニメDVD化される吉田戦車の不条理ギャグ漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ぷりぷり県",
select2: "伝染るんです。",
select3: "殴るぞ",
select4: "戦え！軍人くん",
result_id: 2
},
{ 
content: "次のうち映画「ドラゴンボールZとびっきりの最強対最強」に登場したクウラの部下は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ユダ",
select2: "サウザー",
select3: "シュウ",
select4: "レイ",
result_id: 2
},
{ 
content: "2003年放送のTVアニメ「明日のナージャ」で主題歌を歌った女性歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "谷村有美",
select2: "本田美奈子",
select3: "荻野目洋子",
select4: "石川秀美",
result_id: 2
},
{ 
content: "人形劇「プリンプリン物語」で主題歌と、ヒロインのプリンセス・プリンプリンの声を演じていたアイドルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "倉田まり子",
select2: "河合菜保子",
select3: "香坂みゆき",
select4: "石川ひとみ",
result_id: 4
},
{ 
content: "矢沢愛の漫画「ご近所物語」で主人公・幸田実果子がめざしているのはどんな職業？",
result: 0,
sum: 0,
user_id: 1,
select1: "栄養士",
select2: "服飾デザイナー",
select3: "スタイリスト",
select4: "コピーライター",
result_id: 2
},
{ 
content: "TVアニメ化もされた「あさっての方角。」で知られる漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "山田U太",
select2: "山田Q太",
select3: "山田K太",
select4: "山田J太",
result_id: 4
},
{ 
content: "「電車でGO」の第一作目で体験できる山手線の路線は東京からどこの駅の間？",
result: 0,
sum: 0,
user_id: 1,
select1: "上野の写真",
select2: "原宿の写真",
select3: "渋谷の写真",
select4: "？？？の写真",
result_id: 3
},
{ 
content: "その名前は、インドネシア語で「声」という意味に由来するアニメ「うたわれるもの」の主題歌で知られる女性歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "yozuca",
select2: "Suara",
select3: "eufonius",
select4: "ゆうまお",
result_id: 2
},
{ 
content: "ゲーム「バイオハザードガンサバイバー」の主人公である私立探偵は？",
result: 0,
sum: 0,
user_id: 1,
select1: "アーク・トンプソン",
select2: "ジル・バレンタイン",
select3: "クリス・レッドフィールド",
select4: "レオン・S・ケネディ",
result_id: 1
},
{ 
content: "中国と同盟を結びアメリカと敵対しているという架空の日本を舞台とした福島聡の漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "機動旅団十福神",
select2: "機動旅団八福神",
select3: "機動旅団九福神",
select4: "機動旅団七福神",
result_id: 2
},
{ 
content: "アニメ「アイドル伝説えり子」で主人公・田村えり子の声を演じた声優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "松井菜桜子",
select2: "矢島晶子",
select3: "水谷優子",
select4: "かないみか",
result_id: 2
},
{ 
content: "2004年にナムコから発売されたPS2用ソフト「塊魂」の挿入歌で、「カタマリたいの」を歌ったのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "松崎しげる",
select2: "浅香唯",
select3: "チャーリー・コーセイ",
select4: "水森亜土",
result_id: 2
},
{ 
content: "特撮番組「バトルフィーバーJ」で倉間鉄山将軍を演じた往年の時代劇俳優は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "東千代之介",
select2: "大友柳太郎",
select3: "大河内伝右衛門",
select4: "市川歌右衛門",
result_id: 1
},
{ 
content: "ファミコンゲーム「京都花の密室殺人事件」や「京都財テク殺人事件」の原作を手がけた作家は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "松本清張",
select2: "山村美紗",
select3: "西村京太郎",
select4: "内田康夫",
result_id: 2
},
{ 
content: "吉田戦車の不条理漫画「伝染るんです。」に登場するカブト虫の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "伊藤さん",
select2: "斎藤さん",
select3: "加藤さん",
select4: "安藤さん",
result_id: 2
},
{ 
content: "2009年7月にスタートするTVアニメ「さよなら絶望先生」第3シリーズのタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "惨・さよなら絶望先生",
select2: "懺・さよなら絶望先生",
select3: "酸・さよなら絶望先生",
select4: "散・さよなら絶望先生",
result_id: 2
},
{ 
content: "永野護の漫画「ファイブスター物語」が不定期連載されているアニメ雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ファンロード",
select2: "月刊アニメージュ",
select3: "月刊アニメディア",
select4: "月刊ニュータイプ",
result_id: 4
},
{ 
content: "日本三大祭の一つ・神田祭で2009年に史上初めてアニメキャラクターとして山車になったのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "野原しんのすけ",
select2: "ドラえもん",
select3: "両津勘吉",
select4: "ケロロ軍曹",
result_id: 4
},
{ 
content: "次のうち実際にある漫画のタイトルはどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "火曜サスペンス殺人事件",
select2: "月曜ドラマランド殺人事件",
select3: "土曜ワイド殺人事件",
select4: "木曜スペシャル殺人事件",
result_id: 3
},
{ 
content: "2009年よりインフォレストから刊行される、休刊したアニメ雑誌を引き継いだ新雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ファンロード　改",
select2: "ファンロード　新",
select3: "ファンロード　続",
select4: "ファンロード　再",
result_id: 1
},
{ 
content: "次のスーパー戦隊に登場するロボットのうち変形しないのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ダイデンジン",
select2: "サンバルカンロボ",
select3: "ゴーグルロボ",
select4: "バトルフィーバーロボ",
result_id: 4
},
{ 
content: "2009年7月放送のTVアニメ「東京マグニチュード8.0」で地震を伝えるキャスター役を演じるアナウンサーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "中野美奈子",
select2: "平井理央",
select3: "滝川クリステル",
select4: "高島彩",
result_id: 3
},
{ 
content: "ロボットアニメのタイトルで「UFOロボ」といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "ダイアポロン",
select2: "ダルタニアス",
select3: "グレンダイザー",
select4: "ダイオージャ",
result_id: 3
},
{ 
content: "（グレンダイザーより分岐）「UFO戦士」といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "ダルタニアス",
select2: "ダイオージャ",
select3: "グレンダイザー",
select4: "ダイアポロン",
result_id: 4
},
{ 
content: "アニメ「機動戦士ガンダム」のキャラクターデザインを担当したのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "美樹本晴彦",
select2: "平井久司",
select3: "村瀬修功",
select4: "安彦良和",
result_id: 4
},
{ 
content: "（ヒデ夕樹より分岐）2006年にリメイクされた「ライオン丸G」で主題歌「風よ光よ」を歌った歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "子門真人",
select2: "串田アキラ",
select3: "水木一郎",
select4: "ヒデ夕樹",
result_id: 2
},
{ 
content: "「戦闘妖精雷風」で知られるSF作家・神林長平がノベライズを手がけたTVアニメは？",
result: 0,
sum: 0,
user_id: 1,
select1: "創聖のアクエリオン",
select2: "ラーゼフォン",
select3: "超重神グラヴィオン",
select4: "ゼーガベイン",
result_id: 2
},
{ 
content: "アニメ「イナズマイレブン」のエンディングテーマにも使用された、Berryz工房のシングル曲は？",
result: 0,
sum: 0,
user_id: 1,
select1: "青春フライトアテンダント",
select2: "青春エレベーターガール",
select3: "青春ナース",
select4: "青春バスガイド",
result_id: 4
},
{ 
content: "浦沢直樹の漫画「20世紀少年」の主人公ケンヂのフルネームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "安藤健児",
select2: "進藤健児",
select3: "工藤健児",
select4: "遠藤健児",
result_id: 4
},
{ 
content: "東京にあるカフェを舞台にした原作・宮本夕生、作画・ねぎしきょうこによる漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "Caf?高円寺で",
select2: "Caf?下北沢で",
select3: "Caf?吉祥寺で",
select4: "Caf?国分寺で",
result_id: 3
},
{ 
content: "次のうち、特撮番組「秘密戦隊ゴレンジャー」に登場しないメカはどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "バリタンク",
select2: "バリキキューン",
select3: "バリドリーン",
select4: "バリコプター",
result_id: 4
},
{ 
content: "ＰＳ２版では「シューティング技能検定」というミニゲームが収録されているシューティングゲームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ＨＵＭＵＲＡ",
select2: "式神の城II",
select3: "トライジール",
select4: "虫姫さま",
result_id: 3
},
{ 
content: "2009年放送の特撮番組「侍戦隊シンケンジャー」で志葉家の家臣・日下部彦馬役を演じている俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "あおい輝彦",
select2: "目黒祐樹",
select3: "加藤剛",
select4: "伊吹吾郎",
result_id: 4
},
{ 
content: "漫画「封神演義」の舞台となっている古代中国の王朝は？",
result: 0,
sum: 0,
user_id: 1,
select1: "漢",
select2: "秦",
select3: "夏",
select4: "殷",
result_id: 4
},
{ 
content: "漫画「スクールランブル」の播磨拳児が飼っていた動物で「ピョートル」といえば何？",
result: 0,
sum: 0,
user_id: 1,
select1: "ブタ",
select2: "ペンギン",
select3: "カエル",
select4: "キリン",
result_id: 4
},
{ 
content: "（キリンより分岐、スクールランブルで）「ナポレオン」といえばどんな動物？",
result: 0,
sum: 0,
user_id: 1,
select1: "カエル",
select2: "ブタ",
select3: "キリン",
select4: "ペンギン",
result_id: 2
},
{ 
content: "（コロッケより分岐、料理行進曲で）2番の歌詞で作っている料理は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ナポリタン",
select2: "コロッケ",
select3: "肉じゃが",
select4: "カレーライス",
result_id: 1
},
{ 
content: "セガのゲーム「シェンムーＩＩ」の舞台になっているのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "香港",
select2: "上海",
select3: "シンガポール",
select4: "マカオ",
result_id: 1
},
{ 
content: "次のうち、TVアニメ「ビーストウォーズ超生命体トランスフォーマー」のコンボイが変形するのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "トラックのイラスト",
select2: "ライオンのイラスト",
select3: "ゴリラのイラスト",
select4: "消防車のイラスト",
result_id: 3
},
{ 
content: "吉田秋生の漫画「BANANA FISH」のバナナフィッシュとは何につけられた名前？",
result: 0,
sum: 0,
user_id: 1,
select1: "マフィア",
select2: "麻薬",
select3: "偽札",
select4: "賭場",
result_id: 2
},
{ 
content: "ニコニコ動画で公開されている作曲家・細江慎治による初音ミクの曲「無限の闇」の動画にイラストを提供した漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "CLAMP",
select2: "赤松健",
select3: "吉崎観音",
select4: "荒木飛呂彦",
result_id: 1
},
{ 
content: "漫画「現在官僚系もふ」の主人公・平山茂夫はどこの省庁の官僚？",
result: 0,
sum: 0,
user_id: 1,
select1: "国土交通省",
select2: "環境省",
select3: "財務省",
select4: "文部科学省",
result_id: 3
},
{ 
content: "漫画好きな書店員が選ぶ「マンガ大賞」の選考対象となるのは単行本が最大何巻までの漫画？",
result: 0,
sum: 0,
user_id: 1,
select1: "8巻",
select2: "4巻",
select3: "6巻",
select4: "10巻",
result_id: 1
},
{ 
content: "四季を舞台にしたアドベンチャー「やるドラ」シリーズで春を舞台にしたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "雪割りの花",
select2: "ダブルキャスト",
select3: "サンパギータ",
select4: "季節を抱きしめて",
result_id: 4
},
{ 
content: "（季節を抱きしめてより分岐）夏を舞台にしたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "雪割りの花",
select2: "ダブルキャスト",
select3: "季節を抱きしめて",
select4: "サンパギータ",
result_id: 2
},
{ 
content: "推理ゲーム「探偵　神宮寺三郎」シリーズの主人公・神宮寺三郎が愛用しているタバコの銘柄は？",
result: 0,
sum: 0,
user_id: 1,
select1: "マルボロ",
select2: "キャメル",
select3: "ハイライト",
select4: "ダンヒル",
result_id: 1
},
{ 
content: "押井守が原案・脚本を手がけた2009年公開のアニメ映画「宮本武蔵-双剣に馳せる夢-」の主題歌を歌う歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "小田和正",
select2: "泉谷しげる",
select3: "山下達郎",
select4: "さだまさし",
result_id: 2
},
{ 
content: "「愛・地球博」のマスコットキャラクターを主役にしたアニメ「モリゾーとキッコロの休日」の監督は誰?",
result: 0,
sum: 0,
user_id: 1,
select1: "高橋良輔",
select2: "庵野秀明",
select3: "宮崎駿",
select4: "富野由悠季",
result_id: 1
},
{ 
content: "2009年公開の劇場版「仮面ライダーディケイド」で歌手のGACKTが変身前を演じる仮面ライダーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "仮面ライダーV3",
select2: "ライダーマン",
select3: "仮面ライダースーパー１",
select4: "仮面ライダー1号",
result_id: 2
},
{ 
content: "アルファ・システムのゲーム「高機動幻想ガンパレード・マーチ」や「式神の城」に登場する謎の組織の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "バンゲリングベイ",
select2: "スペランカー",
select3: "デスクリムゾン",
select4: "セプテントリオン",
result_id: 4
},
{ 
content: "格闘ゲーム「鉄拳」シリーズにアンナ・ウィリアムズのコスチュームデザインで参加したことがある漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "桂正和",
select2: "小畑健",
select3: "江川達也",
select4: "永野護",
result_id: 4
},
{ 
content: "LONG SHOT PARTYが歌ったアニメ「続・夏目友人帳」のオープニングテーマは？",
result: 0,
sum: 0,
user_id: 1,
select1: "あの日どこでもドア",
select2: "あの日タイムマシン",
select3: "あの日タケコプター",
select4: "あの日もしもボックス",
result_id: 2
},
{ 
content: "2007年にTVアニメ化されたファンタジー小説「デルトラクエスト」はどこの国で発行された小説？",
result: 0,
sum: 0,
user_id: 1,
select1: "オーストラリア",
select2: "イギリス",
select3: "カナダ",
select4: "デンマーク",
result_id: 1
},
{ 
content: "麻田マモルが歌ったアニメ「太陽の牙ダグラム」のオープニングテーマは？",
result: 0,
sum: 0,
user_id: 1,
select1: "さらばかなしき日々よ",
select2: "さらばたのしき日々よ",
select3: "さらばいとしき日々よ",
select4: "さらばやさしき日々よ",
result_id: 4
},
{ 
content: "次の特撮ヒーローのうち普段の使用武器の中に剣がないのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "デカレッド",
select2: "ライザーグレン",
select3: "セイザーリオン",
select4: "マジレッド",
result_id: 1
},
{ 
content: "アニメ「新世紀エヴァンゲリオン」第19回で、加持リョウジが菜園で水を撒いていたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "キャベツの写真",
select2: "ナスの写真",
select3: "トマトの写真",
select4: "スイカの写真",
result_id: 4
},
{ 
content: "青木雄二プロダクションの漫画「新・ナニワ金融道」が連載されている雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊プレイボーイ",
select2: "週刊大衆",
select3: "アサヒ芸能",
select4: "週刊SPA",
result_id: 3
},
{ 
content: "（週刊SPA！より分岐）漫画「ナニワ銭道」が連載されている雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊大衆",
select2: "アサヒ芸能",
select3: "週刊SPA",
select4: "週刊プレイボーイ",
result_id: 2
},
{ 
content: "アニメ「ガンダム」シリーズに登場するエースパイロットで「赤い彗星」とあだ名されるのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "シャア・アズナブル",
select2: "アナベル・ガトー",
select3: "ランバ・ラル",
select4: "ララァ・スン",
result_id: 1
},
{ 
content: "（シャア・アズナブルより分岐）「青い巨星」とあだ名されるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "シャア・アズナブル",
select2: "ララァ・スン",
select3: "ランバ・ラル",
select4: "アナベル・ガトー",
result_id: 3
},
{ 
content: "アニメ「ゲッターロボ」でゲッター1号を操縦するのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "流竜馬",
select2: "車弁慶",
select3: "神隼人",
select4: "一文字號",
result_id: 1
},
{ 
content: "（流竜馬より分岐）アニメ「ゲッターロボ號」でゲッターロボ號を操縦するのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "神隼人",
select2: "一文字號",
select3: "流竜馬",
select4: "車弁慶",
result_id: 2
},
{ 
content: "漫画「ウイングマン」で変身時間残り3分間だけ使うことができるウイングマンの必殺技は？",
result: 0,
sum: 0,
user_id: 1,
select1: "デルタエンド",
select2: "スプリクトフラッシュ",
select3: "ファイナルビーム",
select4: "ヒートショック",
result_id: 1
},
{ 
content: "アニメ「機動戦士ガンダムSEED」で、地球軍とザフト軍が全面戦争をするきっかけとなった事件は？",
result: 0,
sum: 0,
user_id: 1,
select1: "血のクリスマス",
select2: "血のバレンタイン",
select3: "血のハロウィン",
select4: "血のエイプリルフール",
result_id: 2
},
{ 
content: "アニメ「スレイヤーズ」で主人公リナが苦手なものは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ナメクジ",
select2: "カエル",
select3: "ミミズ",
select4: "サソリ",
result_id: 1
},
{ 
content: "小説「住めば都のコスモス荘」に登場するウサギ型宇宙人の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "タニケイ",
select2: "シムラケン",
select3: "ウエキヒトシ",
select4: "ハナハジメ",
result_id: 4
},
{ 
content: "教科書会社の学校図書と共同で2011年より小学校で用いられる教科書を制作したゲーム会社は？",
result: 0,
sum: 0,
user_id: 1,
select1: "コナミ",
select2: "カプコン",
select3: "コーエーテクモゲームス",
select4: "バンダイナムコゲームス",
result_id: 4
},
{ 
content: "かつて「ファミコン通信」を発行していた出版社は？",
result: 0,
sum: 0,
user_id: 1,
select1: "アスキー",
select2: "角川書店",
select3: "秋田書店",
select4: "徳間書店",
result_id: 1
},
{ 
content: "アニメ「機動戦士ガンダム」に登場する、ホワイトベースのコック長は？",
result: 0,
sum: 0,
user_id: 1,
select1: "オオムラ",
select2: "タムラ",
select3: "ナカムラ",
select4: "キムラ",
result_id: 2
},
{ 
content: "2010年4月、埼玉の魅力を全国に発信する「埼玉応援団（コバトン倶楽部）」のメンバーとなった漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "葉鳥ビスコ",
select2: "松本ぷりっつ",
select3: "美水かがみ",
select4: "二ノ宮知子",
result_id: 4
},
{ 
content: "2010年にインターネット上で「美人すぎる漫画家」として話題となった中国の漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "冬達",
select2: "夏達",
select3: "秋達",
select4: "春達",
result_id: 2
},
{ 
content: "天道総司が変身するのは仮面ライダー何？",
result: 0,
sum: 0,
user_id: 1,
select1: "鶴の折り紙",
select2: "兜の折り紙",
select3: "蝉の折り紙",
select4: "？？？の折り紙",
result_id: 2
},
{ 
content: "漫画「鉄腕アトム」を描いた漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "横山光輝",
select2: "手塚治虫",
select3: "石ノ森章太郎",
select4: "ゆうきまさみ",
result_id: 2
},
{ 
content: "（手塚治虫より分岐）「鉄腕バーディ」を描いた漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "手塚治虫",
select2: "ゆうきまさみ",
select3: "横山光輝",
select4: "石ノ森章太郎",
result_id: 2
},
{ 
content: "漫画「うる星やつら」で牛の姿に変身するラムの元フィアンセといえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "ユダ",
select2: "シン",
select3: "サウザー",
select4: "レイ",
result_id: 4
},
{ 
content: "自らの人生を題材とした自伝的漫画「激マン！」を描いている漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "藤子不二雄A",
select2: "永井豪",
select3: "さいとうたかを",
select4: "つのだじろう",
result_id: 2
},
{ 
content: "2009年公開の映画「大怪獣バトルウルトラ銀河伝説」の主題歌「星のように…」を歌った女性歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "青山テルマ",
select2: "MISIA",
select3: "平原綾香",
select4: "Cocco",
result_id: 2
},
{ 
content: "OVA「YAMATO2520」の主題歌「明日の君を守りたい」を歌っていたグループは？",
result: 0,
sum: 0,
user_id: 1,
select1: "SMAP",
select2: "TOKIO",
select3: "少年隊",
select4: "光GENJI",
result_id: 2
},
{ 
content: "浦沢直樹の漫画「PLUTO」の冒頭で破壊されてしまうスイスのロボットは？",
result: 0,
sum: 0,
user_id: 1,
select1: "アルプス",
select2: "グランドジョラス",
select3: "マッターホルン",
select4: "モンブラン",
result_id: 4
},
{ 
content: "アニメ「アルプスの少女ハイジ」の原作者は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "ウィーダ",
select2: "ヨハンナ・スピリ",
select3: "エドモンド・デ・アミーチス",
select4: "スターリング・ノース",
result_id: 2
},
{ 
content: "アニメ「新機動戦記ガンダムW」で、ウイングガンダムのパイロットは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "トロワー・バートン",
select2: "カトル・ラバーバ・ウィナー",
select3: "ゼクス・マーキス",
select4: "ヒイロ・ユイ",
result_id: 4
},
{ 
content: "漫画「現在官僚系もふ」の主人公・平山茂夫はどこの省庁の官僚？",
result: 0,
sum: 0,
user_id: 1,
select1: "財務省",
select2: "国土交通省",
select3: "文部科学省",
select4: "環境省",
result_id: 1
},
{ 
content: "アニメ「てんとう虫の歌」で事故で両親を亡くした兄弟は何人？",
result: 0,
sum: 0,
user_id: 1,
select1: "8人",
select2: "7人",
select3: "6人",
select4: "5人",
result_id: 2
},
{ 
content: "「ギターヒーロー」シリーズなどの作品を発売しているサンタモニカに本社を置く世界最大のゲームソフト会社は？",
result: 0,
sum: 0,
user_id: 1,
select1: "アクティビジョン・ツイスター",
select2: "アクティビジョン・サンダーボルト",
select3: "アクティビジョン・エクスプロージョン",
select4: "アクティビジョン・ブリザード",
result_id: 4
},
{ 
content: "ゲーム「魔神転生2」でプレイヤーが所属する悪魔と戦う組織の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "レジスタンス",
select2: "プロテスタント",
select3: "コントラ",
select4: "パルチザン",
result_id: 4
},
{ 
content: "アニメ「機動戦士ガンダム」で主人公と行動をともにする戦災孤児は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ユキオ、クマゾー、アカリ",
select2: "モーリス、メーテル、リンク",
select3: "シンタ、クム",
select4: "カツ、レツ、キッカ",
result_id: 4
},
{ 
content: "（カツ、レツ、キッカより分岐）「交響詩篇エウレカセブン」で主人公たちと行動をともにする戦災孤児は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ユキオ、クマゾー、アカリ",
select2: "モーリス、メーテル、リンク",
select3: "シンタ、クム",
select4: "カツ、レツ、キッカ",
result_id: 2
},
{ 
content: "特撮番組「電磁戦隊メガレンジャー」で敵の幹部シボレナ役を演じたセクシー女優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "水谷ケイ",
select2: "七瀬理香",
select3: "及川奈央",
select4: "城麻美",
result_id: 4
},
{ 
content: "（城麻美より分岐）「炎神戦隊ゴーオンジャー」で敵の幹部ケガレシアを演じたセクシー女優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "七瀬理香",
select2: "及川奈央",
select3: "城麻美",
select4: "水谷ケイ",
result_id: 2
},
{ 
content: "漫画「ハイスクール奇面組」の奇面組のメンバーで家が酒屋なのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "一堂零",
select2: "冷越豪",
select3: "出瀬潔",
select4: "大間仁",
result_id: 2
},
{ 
content: "東映の特撮番組によくクレジットされる東映のプロデューサー集団のペンネームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "照樹務",
select2: "八手三郎",
select3: "東堂いずみ",
select4: "矢立肇",
result_id: 2
},
{ 
content: "（八手三郎より分岐）東映アニメーションのアニメによくクレジットされる同社のペンネームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "八手三郎",
select2: "矢立肇",
select3: "照樹務",
select4: "東堂いずみ",
result_id: 4
},
{ 
content: "2010年1月より、TVアニメ「ちびまる子ちゃん」のOP曲「おどるポンポコリン」を歌っている女性歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "木村カエラ",
select2: "青山テルマ",
select3: "加藤ミリヤ",
select4: "西野カナ",
result_id: 1
},
{ 
content: "フライトシューティングゲーム「エースコンバット04」のサブタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "蒼空の覇者",
select2: "妖精の舞う空",
select3: "エレクトロスフィア",
select4: "シャッタードスカイ",
result_id: 4
},
{ 
content: "（シャッタードスカイより分岐）「エースコンバット3」のサブタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "エレクトロスフィア",
select2: "シャッタードスカイ",
select3: "妖精の舞う空",
select4: "蒼空の覇者",
result_id: 1
},
{ 
content: "漫画「ハチミツとクローバー」で主人公・竹本祐太は浜田山美術大学の何科に通っている？",
result: 0,
sum: 0,
user_id: 1,
select1: "彫刻科",
select2: "陶芸科",
select3: "建築科",
select4: "油絵科",
result_id: 3
},
{ 
content: "ウルトラマンや怪獣が銀河最強武闘会に出場するという内容の、「コミックボンボン」に連載された漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ウルトラマン超戦士激伝",
select2: "ウルトラマン超闘士激伝",
select3: "ウルトラマン超戦士列伝",
select4: "ウルトラマン超闘士列伝",
result_id: 2
},
{ 
content: "特撮番組「ウルトラセブン」に登場する宇宙ロボット・キングジョーは何体に分離する？",
result: 0,
sum: 0,
user_id: 1,
select1: "2体",
select2: "4体",
select3: "5体",
select4: "3体",
result_id: 2
},
{ 
content: "2010年7月より「ガンダムエース」で「機動武闘伝Gガンダム」の漫画版を連載するのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ゆうきまさみ",
select2: "島本和彦",
select3: "江川達也",
select4: "藤田和日郎",
result_id: 2
},
{ 
content: "声優・豊崎愛生が本人名義でリリースしたシングル「ぼくを探して」の作曲を担当したミュージシャンは？",
result: 0,
sum: 0,
user_id: 1,
select1: "UA",
select2: "Chara",
select3: "MISIA",
select4: "Cocco",
result_id: 2
},
{ 
content: "漫画「魔法先生ねぎま！」に登場する生徒で実は地縛霊なのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "エヴァンジェリン",
select2: "絡繰茶々丸",
select3: "龍宮真名",
select4: "相坂さよ",
result_id: 4
},
{ 
content: "アメリカの人気コミック「スーパーマン」で主人公が生まれた星の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "クリプトン星",
select2: "ネオン星",
select3: "アルゴン星",
select4: "キセノン星",
result_id: 1
},
{ 
content: "2010年7月に公開される映画「エアベンダー」で、日本語吹き替え版のセリフを監修したゲームクリエイターは？",
result: 0,
sum: 0,
user_id: 1,
select1: "小島秀夫",
select2: "田尻智",
select3: "イシイジロウ",
select4: "シブサワ・コウ",
result_id: 4
},
{ 
content: "2004年に公開された大友克洋監督のアニメ映画「スチームボーイ」で、主人公の少年レイの声を演じた女優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "鈴木保奈美",
select2: "鈴木紗理奈",
select3: "鈴木杏",
select4: "鈴木京香",
result_id: 3
},
{ 
content: "2010年8月に双葉社から創刊される美少女マンガ雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "COMICすもも",
select2: "COMICすいか",
select3: "COMICれもん",
select4: "COMICめろん",
result_id: 1
},
{ 
content: "PS3用ソフト「龍が如く３」「龍が如く４」のゲーム内で実際に遊べるゲームはどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "三国志大戦",
select2: "Answer×Answer",
select3: "甲虫王者ムシキング",
select4: "麻雀格闘倶楽部",
result_id: 2
},
{ 
content: "（京極夏彦より分岐）特撮番組「ウルトラマンメビウス」の脚本を手がけたこともある直木賞作家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "京極夏彦",
select2: "石田衣良",
select3: "朱川湊人",
select4: "重松清",
result_id: 3
},
{ 
content: "「大怪獣ヤンガリー」といえばどこの国の怪獣映画？",
result: 0,
sum: 0,
user_id: 1,
select1: "インド",
select2: "フィリピン",
select3: "北朝鮮",
select4: "韓国",
result_id: 4
},
{ 
content: "（韓国より分岐）「プルガサリ」といえばどこの国の怪獣映画？",
result: 0,
sum: 0,
user_id: 1,
select1: "インド",
select2: "北朝鮮",
select3: "フィリピン",
select4: "韓国",
result_id: 2
},
{ 
content: "堀越耕平の漫画「逢魔ヶ刻動物園」で逢魔ヶ刻動物園の園長はどんな動物の姿をしている？",
result: 0,
sum: 0,
user_id: 1,
select1: "ライオン",
select2: "ウサギ",
select3: "ゾウ",
select4: "ウシ",
result_id: 2
},
{ 
content: "2009年にフランスの最高勲章「レジオン・ド・ヌール」を受章した日本の漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "竹宮恵子",
select2: "池田理代子",
select3: "美水すずえ",
select4: "山本鈴美香",
result_id: 2
},
{ 
content: "「東京ラブストーリー」で知られる漫画家・柴門ふみのデビュー作は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ハエ男フンばる",
select2: "コウモリ男フンばる",
select3: "クモ男フンばる",
select4: "サソリ男フンばる",
result_id: 3
},
{ 
content: "1977年にタカラから発売された人形で大きな木の家に住んでいる女の子の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "こえだちゃん",
select2: "ぷりっつちゃん",
select3: "ふらんちゃん",
select4: "とっぽちゃん",
result_id: 1
},
{ 
content: "ファッション雑誌「non-no」に連載中の漫画「Nonstop Days」はファッションモデルである誰の半生を描いた漫画？",
result: 0,
sum: 0,
user_id: 1,
select1: "杏",
select2: "本田翼",
select3: "岸本セシル",
select4: "佐々木希",
result_id: 4
},
{ 
content: "（建築家より分岐、ハチクロで）ヒロイン・花本はぐみは何科に通っている？",
result: 0,
sum: 0,
user_id: 1,
select1: "彫刻科",
select2: "油絵科",
select3: "陶芸科",
select4: "建築科",
result_id: 2
},
{ 
content: "アニメ「巨人の星」でオズマが1年間という期限付きで入団したプロ野球球団はどこ？",
result: 0,
sum: 0,
user_id: 1,
select1: "広島東洋カープ",
select2: "中日ドラゴンズ",
select3: "大洋ホエールズ",
select4: "ヤクルトアトムズ",
result_id: 2
},
{ 
content: "ゲーム「メタルギアソリッド3」で、サバイバルナイフの代わりに使用できるアイテムは？",
result: 0,
sum: 0,
user_id: 1,
select1: "フォーク",
select2: "トング",
select3: "ハシ",
select4: "スプーン",
result_id: 1
},
{ 
content: "1980年にアニメ雑誌「ファンロード」を創刊した出版社は？",
result: 0,
sum: 0,
user_id: 1,
select1: "銀英社",
select2: "インフォレスト",
select3: "ラポート社",
select4: "大都社",
result_id: 3
},
{ 
content: "特撮番組「仮面ライダースーパー1」で、スーパー1が使うファイブハンドのうち赤色の腕はどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "スーパーハンド",
select2: "パワーハンド",
select3: "レーダーハンド",
select4: "エレキハンド",
result_id: 2
},
{ 
content: "（パワーハンドより分岐、仮面ライダースーパー1で）金色の腕はどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "レーダーハンド",
select2: "スーパーハンド",
select3: "エレキハンド",
select4: "パワーハンド",
result_id: 1
},
{ 
content: "2009年に発売されたWii用ゲーム「戦国無双3」に搭載された、懐かしのファミコンソフトとコラボしたモードは？",
result: 0,
sum: 0,
user_id: 1,
select1: "「謎の村雨城」モード",
select2: "「忍者龍剣伝」モード",
select3: "「影の伝説」モード",
select4: "「新・鬼ヶ島」モード",
result_id: 1
},
{ 
content: "ゲーム「To Heart2」に登場するルーシー・マリア・ミソラが自分の故郷だという惑星は？",
result: 0,
sum: 0,
user_id: 1,
select1: "大熊座47番星第3惑星",
select2: "くじら座47番星第3惑星",
select3: "こと座47番星第3惑星",
select4: "白鳥座47番星第3惑星",
result_id: 1
},
{ 
content: "小説「撲殺天使ドクロちゃん」の主人公ドクロちゃんの好物は？",
result: 0,
sum: 0,
user_id: 1,
select1: "タバスコ",
select2: "ケチャップ",
select3: "マヨネーズ",
select4: "チーズ",
result_id: 3
},
{ 
content: "2008年にPS3とXbox360で発売されたサッカーゲーム「FIFAストリート3」で1チームの選手の人数は何人？",
result: 0,
sum: 0,
user_id: 1,
select1: "11人",
select2: "9人",
select3: "5人",
select4: "7人",
result_id: 3
},
{ 
content: "アニメ「装甲騎兵ボトムズ」に登場する人型の兵器「AT」のTは何の略？",
result: 0,
sum: 0,
user_id: 1,
select1: "トレーサー",
select2: "トルーパー",
select3: "トータル",
select4: "タクティカル",
result_id: 2
},
{ 
content: "（トルーパーより分岐）「ガサラキ」に登場する人型の兵器「TA」のTは何の略？",
result: 0,
sum: 0,
user_id: 1,
select1: "トレーサー",
select2: "トータル",
select3: "トルーパー",
select4: "タクティカル",
result_id: 4
},
{ 
content: "2009年11月に、法律により「暴力的なゲーム、および武器をモチーフとした玩具」を禁止した南米の国は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ベネズエラ",
select2: "ウルグアイ",
select3: "パラグアイ",
select4: "コロンビア",
result_id: 1
},
{ 
content: "特撮番組「仮面ライダークウガ」で、クウガは警察から何と呼ばれている？",
result: 0,
sum: 0,
user_id: 1,
select1: "未確認生命体第4号",
select2: "未確認生命体第3号",
select3: "未確認生命体第1号",
select4: "未確認生命体第5号",
result_id: 1
},
{ 
content: "2009年の映画「仮面ライダーW＆ディケイドMOVIE大戦2010」で、仮面ライダースカルに変身する探偵・鳴海壮吉を演じた歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "吉川晃司",
select2: "氷室京介",
select3: "布袋寅泰",
select4: "大友康平",
result_id: 1
},
{ 
content: "青池保子の長編漫画「エロイカより愛をこめて」の「エロイカ」とはドイツ語でどういう意味？",
result: 0,
sum: 0,
user_id: 1,
select1: "スパイ",
select2: "祖国",
select3: "英雄",
select4: "戦場",
result_id: 3
},
{ 
content: "怪獣ゴジラの鳴き声はどんな楽器の音をテープで逆回転させたもの？",
result: 0,
sum: 0,
user_id: 1,
select1: "チェロ",
select2: "コントラバス",
select3: "バイオリン",
select4: "ヴィオラ",
result_id: 2
},
{ 
content: "「新世紀エヴァンゲリオン」の登場人物、鈴原トウジと相田ケンスケの名前の引用元である村上龍の小説は？",
result: 0,
sum: 0,
user_id: 1,
select1: "すべての男は消耗品である",
select2: "だいじょうぶマイ・フレンド",
select3: "愛と幻想のファシズム",
select4: "コインロッカー・ベイビーズ",
result_id: 3
},
{ 
content: "1957年に放送された「赤胴鈴之助」のラジオドラマに小学生で出演していたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "樹木希林",
select2: "吉永小百合",
select3: "都はるみ",
select4: "泉ピン子",
result_id: 2
},
{ 
content: "（鳥山明より分岐）「LOVE&DESTROY」のキャラクターデザインを担当した漫画家は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "鳥山明",
select2: "藤島康介",
select3: "江川達也",
select4: "桂正和",
result_id: 4
},
{ 
content: "アニメ「ふたりはプリキュア」で美墨なぎさが所属しているのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "バスケット部",
select2: "サッカー部",
select3: "科学部",
select4: "ラクロス部",
result_id: 4
},
{ 
content: "（ラクロス部より分岐、プリキュアで）藤Pが所属しているのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "バスケット部",
select2: "ラクロス部",
select3: "サッカー部",
select4: "科学部",
result_id: 3
},
{ 
content: "マッドサイエンティストの祖父と暮らす中学生の小林彩を主人公とした柏林のギャグマンガは？",
result: 0,
sum: 0,
user_id: 1,
select1: "はっきねん",
select2: "しゅーまっは",
select3: "あろんそ",
select4: "らいこねん",
result_id: 2
},
{ 
content: "次のうち漫画「キン肉マンII世」に登場した超人はどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "ガレッジセール",
select2: "バナナマン",
select3: "チュートリアル",
select4: "ハリセンボン",
result_id: 2
},
{ 
content: "かつて「週刊少年マガジン」誌上で「ウルトラマン」の漫画版を連載した漫画家は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "さいとう・たかを",
select2: "あだち充",
select3: "楳図かずお",
select4: "石川賢",
result_id: 3
},
{ 
content: "（楳図かずおより分岐）「週刊少年サンデー」誌上で「ウルトラマンタロウ」の漫画版を連載した漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "楳図かずお",
select2: "さいとう・たかを",
select3: "あだち充",
select4: "石川賢",
result_id: 4
},
{ 
content: "ゲーム「ときめきメモリアルドラマシリーズ　虹色の青春」のヒロイン・虹野沙希は何部のマネージャー？",
result: 0,
sum: 0,
user_id: 1,
select1: "サッカー部",
select2: "バスケットボール部",
select3: "テニス部",
select4: "水泳部",
result_id: 1
},
{ 
content: "人形劇「プリンプリン物語」で主題歌と、ヒロインのプリンセス・プリンプリンの声を演じていたアイドルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "河合奈保子",
select2: "倉田まり子",
select3: "石川ひとみ",
select4: "香坂みゆき",
result_id: 3
},
{ 
content: "漫画「焼きたてジャぱん」に登場する江戸川コナンそっくりのキャラクターは？",
result: 0,
sum: 0,
user_id: 1,
select1: "多摩川コナン",
select2: "鬼怒川コナン",
select3: "隅田川コナン",
select4: "利根川コナン",
result_id: 4
},
{ 
content: "特撮番組「百獣戦隊ガオレンジャー」の主題歌を歌った歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "サイキックラバー",
select2: "高取ヒデアキ",
select3: "風雅なおと",
select4: "山形ユキオ",
result_id: 4
},
{ 
content: "（山形ユキオより分岐）「特捜戦隊デカレンジャー」の主題歌を歌った歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "山形ユキオ",
select2: "風雅なおと",
select3: "高取ヒデアキ",
select4: "サイキックラバー",
result_id: 4
},
{ 
content: "モデルにスカウトされた紫と服飾デザイン学校に通うジョージの恋を描いた矢沢あいの漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "エスケープ",
select2: "天使なんかじゃない",
select3: "パラダイス・キス",
select4: "バラードまではそばにいて",
result_id: 3
},
{ 
content: "Wii用ゲーム「ゼルダの伝説トワイライトプリンセス」で人を空間転送する能力を持っているのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "おぼっちゃん",
select2: "おじょうちゃん",
select3: "おじちゃん",
select4: "おばちゃん",
result_id: 4
},
{ 
content: "（冷越豪より分岐、奇面組で）家が本屋なのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "物星大",
select2: "冷越豪",
select3: "一堂零",
select4: "大間仁",
result_id: 1
},
{ 
content: "1987年放送のTVアニメ「アニメ三銃士」に登場する次のキャラクターのうち女性なのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "ダルタニャン",
select2: "ポルトス",
select3: "アトス",
select4: "アラミス",
result_id: 4
},
{ 
content: "ナムコのアクションゲーム「源平討魔伝」の中でゲームオーバー時に表示される漢字といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "愛",
select2: "然",
select3: "完",
select4: "徳",
result_id: 3
},
{ 
content: "ゲーム「ブレスオブファイア」の主人公・リュウが変身できる生き物は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ペガサス",
select2: "虎",
select3: "鳥",
select4: "竜",
result_id: 4
},
{ 
content: "2009～10年に放送されたTVアニメ「しゅごキャラ」第3期のタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "しゅごキャラパーティー",
select2: "しゅごキャラフィーバー",
select3: "しゅごキャラキューティー",
select4: "しゅごキャラビューティー",
result_id: 1
},
{ 
content: "アニメ「機動戦士ガンダム」の放送当時のスポンサーだった玩具メーカーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "トミー",
select2: "クローバー",
select3: "タカトクトイス",
select4: "ポピー",
result_id: 2
},
{ 
content: "漫画「女帝」で主人公の彩香が目指すのはどこの女帝？",
result: 0,
sum: 0,
user_id: 1,
select1: "祇園",
select2: "銀座",
select3: "博多",
select4: "新地",
result_id: 2
},
{ 
content: "セガのアクションゲーム「テディボーイブルース」のボーナスステージに登場する元アイドル歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "山口百恵",
select2: "熊谷真実",
select3: "石野陽子",
select4: "中山美穂",
result_id: 3
},
{ 
content: "アニメ「あらいぐまラスカル」の舞台となっている国はどこ？",
result: 0,
sum: 0,
user_id: 1,
select1: "アメリカ",
select2: "オーストラリア",
select3: "フィンランド",
select4: "カナダ",
result_id: 1
},
{ 
content: "弟や妹のために、病気で入院した母親に代わり慣れない料理に挑戦するイケメン高校生・早川律を主人公とする小沢真理の漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "銀のグラス",
select2: "銀のスプーン",
select3: "銀のナイフ",
select4: "銀のフォーク",
result_id: 2
},
{ 
content: "特撮番組「仮面ライダー」で主人公本郷猛役を当初演じる予定だった俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "中村敦夫",
select2: "江守徹",
select3: "田宮二郎",
select4: "近藤正臣",
result_id: 4
},
{ 
content: "1975年放送のロボットアニメ「鋼鉄ジーグ」で鋼鉄ジーグの頭部に変形するサイボーグの主人公は？",
result: 0,
sum: 0,
user_id: 1,
select1: "司馬遼太郎",
select2: "司馬宙",
select3: "司馬光",
select4: "司馬遷",
result_id: 2
},
{ 
content: "「サザエさん」のカツオ役でおなじみの声優・冨永みーなが子役時代にレギュラー出演していた特撮番組は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ウルトラマンレオ",
select2: "ウルトラマンタロウ",
select3: "ウルトラマン80",
select4: "ウルトラマンエース",
result_id: 1
},
{ 
content: "漫画「キン肉マン」でキン肉マンと結婚し王妃となったのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "ナムルの写真",
select2: "ラーメン？の写真",
select3: "ゼリー？の写真",
select4: "ビビンバの写真",
result_id: 4
},
{ 
content: "TVアニメ「あしたのジョー」で矢吹丈の声を演じたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "石橋正次",
select2: "あおい輝彦",
select3: "仲村秀生",
select4: "藤岡重慶",
result_id: 2
},
{ 
content: "アニメ「カレイドスター」の製作に参加した、日本の大手芸能プロダクションは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ホリプロ",
select2: "スターダストプロモーション",
select3: "太田プロ",
select4: "吉本興業",
result_id: 1
},
{ 
content: "OVA「銀河英雄伝説」の主題歌を歌った歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "因幡晃",
select2: "大滝詠一",
select3: "井上陽水",
select4: "小椋佳",
result_id: 4
},
{ 
content: "航空機を操って敵と戦うゲーム「スカイキッド」でプレイヤー1が操作するキャラは？",
result: 0,
sum: 0,
user_id: 1,
select1: "マックス",
select2: "デューク",
select3: "バロン",
select4: "アール",
result_id: 3
},
{ 
content: "（バロンより分岐、スカイキッドで）プレイヤー2が操作するキャラは？",
result: 0,
sum: 0,
user_id: 1,
select1: "アール",
select2: "デューク",
select3: "バロン",
select4: "マックス",
result_id: 4
},
{ 
content: "かつて須藤リカのバックバンドとしてアニメ「海のトリトン」の主題歌を歌ったグループは？",
result: 0,
sum: 0,
user_id: 1,
select1: "アリス",
select2: "海援隊",
select3: "かぐや姫",
select4: "チューリップ",
result_id: 3
},
{ 
content: "アニメ「サザエさん」の舞台はどこ？",
result: 0,
sum: 0,
user_id: 1,
select1: "静岡県",
select2: "埼玉県",
select3: "神奈川県",
select4: "東京都",
result_id: 4
},
{ 
content: "アニメ「タイムボカン」シリーズで、主人公の時ワタルが変身してミレンジョ一味と戦うのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "オタスケマン",
select2: "ヤットデタマン",
select3: "ゼンダマン",
select4: "イッパツマン",
result_id: 2
},
{ 
content: "（冷越豪より分岐、奇面組で）家がケーキ屋なのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "大間仁",
select2: "一堂零",
select3: "出瀬潔",
select4: "冷越豪",
result_id: 1
},
{ 
content: "漫画「ドカベン」で明訓高校野球部を甲子園初出場で優勝に導いた監督は？",
result: 0,
sum: 0,
user_id: 1,
select1: "豊臣秀吉",
select2: "織田信長",
select3: "伊達政宗",
select4: "徳川家康",
result_id: 4
},
{ 
content: "アニメ「魔法の天使クリィミーマミ」で、主人公の声と主題歌を担当した女性歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "大森玲子",
select2: "小幡洋子",
select3: "太田貴子",
select4: "志賀真理子",
result_id: 3
},
{ 
content: "（太田貴子より分岐）「魔法のステージ　ファンシーララ」で、主人公の声と主題歌を担当した女性歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "太田貴子",
select2: "志賀真理子",
select3: "大森玲子",
select4: "小幡洋子",
result_id: 3
},
{ 
content: "岡本倫の漫画「エルフェンリート」の舞台となっている都市は？",
result: 0,
sum: 0,
user_id: 1,
select1: "尾道市",
select2: "鎌倉市",
select3: "松本市",
select4: "浦安市",
result_id: 2
},
{ 
content: "アニメ「ルパン三世」のTVシリーズ第1作でルパン三世が着ているジャケットの色は？",
result: 0,
sum: 0,
user_id: 1,
select1: "緑色",
select2: "赤色",
select3: "ピンク色",
select4: "黄色",
result_id: 1
},
{ 
content: "（緑色より分岐、ルパン三世で）TVシリーズ第2作でルパン三世が着ているジャケットの色は何色？",
result: 0,
sum: 0,
user_id: 1,
select1: "赤色",
select2: "黄色",
select3: "ピンク色",
select4: "緑色",
result_id: 1
},
{ 
content: "漫画「ジョジョの奇妙な冒険」第6部「ストーンオーシャン」の舞台となっている国はどこ？",
result: 0,
sum: 0,
user_id: 1,
select1: "イタリアの国旗",
select2: "フランスの国旗",
select3: "アメリカの国旗",
select4: "イギリスの国旗",
result_id: 3
},
{ 
content: "漫画好きな書店員が選ぶ「マンガ大賞」の選考対象となるのは単行本が最大何巻までの漫画？",
result: 0,
sum: 0,
user_id: 1,
select1: "4巻",
select2: "10巻",
select3: "6巻",
select4: "8巻",
result_id: 4
},
{ 
content: "メキシコ五輪出場をめざす少年、東一郎を主人公にしたアニメ「アニマル1」で描かれているのはどんな競技？",
result: 0,
sum: 0,
user_id: 1,
select1: "ボクシング",
select2: "柔道",
select3: "重量挙げ",
select4: "アマチュアレスリング",
result_id: 4
},
{ 
content: "アニメ「鋼の錬金術師」に登場するロイ・マスタングが炎を生み出すときに使う道具は？",
result: 0,
sum: 0,
user_id: 1,
select1: "手袋",
select2: "ブローチ",
select3: "ハンカチ",
select4: "帽子",
result_id: 1
},
{ 
content: "フライトシューティングゲーム「ゼロ・パイロット銀翼の戦士」の主人公が所属している国は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ヤポン国",
select2: "アキツ国",
select3: "ヤマト国",
select4: "ヤシマ国",
result_id: 3
},
{ 
content: "アニメ専用のCSチャンネルアニメシアターXの親会社であるテレビ局は？",
result: 0,
sum: 0,
user_id: 1,
select1: "テレビ朝日",
select2: "TBS",
select3: "テレビ東京",
select4: "フジテレビ",
result_id: 3
},
{ 
content: "コーエーのSLG「信長の野望　全国版」で全国版モードのマップに登場する国は全部で何カ国？",
result: 0,
sum: 0,
user_id: 1,
select1: "50",
select2: "42",
select3: "46",
select4: "38",
result_id: 1
},
{ 
content: "アニメ「北斗の拳」でレイが使う必殺拳は？",
result: 0,
sum: 0,
user_id: 1,
select1: "南斗白鷺拳",
select2: "南斗鳳凰拳",
select3: "南斗水鳥拳",
select4: "南斗紅鶴拳",
result_id: 3
},
{ 
content: "（南斗水鳥拳より分岐、北斗の拳で）ユダが使う必殺拳は？",
result: 0,
sum: 0,
user_id: 1,
select1: "南斗鳳凰拳",
select2: "南斗紅鶴拳",
select3: "南斗白鷺拳",
select4: "南斗水鳥拳",
result_id: 2
},
{ 
content: "アニメ「うる星やつら」に登場するどこからともなく現れる僧は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "ぶどう",
select2: "さくらんぼ",
select3: "すいか",
select4: "ばなな",
result_id: 2
},
{ 
content: "（マッハロッドより分岐）「星雲仮面マシンマン」でマシンマンが乗るマシンは？",
result: 0,
sum: 0,
user_id: 1,
select1: "マッハロッド",
select2: "ハヤブサオー",
select3: "ドルフィン",
select4: "ライジンゴー",
result_id: 3
},
{ 
content: "テクモから発売されたゲーム「キャプテン翼」シリーズで翼が身に付けた伝説の必殺シュートは？",
result: 0,
sum: 0,
user_id: 1,
select1: "タイフーン",
select2: "ハリケーン",
select3: "サイクロン",
select4: "ハムシーン",
result_id: 3
},
{ 
content: "2005年公開の劇場アニメ「AIR」の監督は？",
result: 0,
sum: 0,
user_id: 1,
select1: "高橋良輔",
select2: "出崎統",
select3: "渡部高志",
select4: "石原立也",
result_id: 2
},
{ 
content: "（出崎統より分岐）TVアニメ「AIR」の監督は？",
result: 0,
sum: 0,
user_id: 1,
select1: "渡部高志",
select2: "出崎統",
select3: "石原立也",
select4: "高橋良輔",
result_id: 3
},
{ 
content: "横山光輝の漫画「バビル2世」の続編のタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "その中010",
select2: "その名は110",
select3: "その名は001",
select4: "その名は101",
result_id: 4
},
{ 
content: "漫画「スクールランブル」で烏丸大路が好きな妖怪は？",
result: 0,
sum: 0,
user_id: 1,
select1: "座敷わらし",
select2: "天狗",
select3: "河童",
select4: "雪女",
result_id: 3
},
{ 
content: "アニメ「BLOOD＋」「牙」などを手がけたアニプレックスはどこのグループ会社？",
result: 0,
sum: 0,
user_id: 1,
select1: "avex",
select2: "ソニー",
select3: "ビクター",
select4: "東芝",
result_id: 2
},
{ 
content: "主演したアニメ「ヴァイスクロイツ」の原作を自ら手がけた声優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "結城比呂",
select2: "関智一",
select3: "子安武人",
select4: "三木眞一郎",
result_id: 3
},
{ 
content: "永井豪原作のロボットアニメ「マジンガーZ」でマジンガーZに乗り込む主人公は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "宇門大介",
select2: "兜甲児",
select3: "剣鉄也",
select4: "流竜馬",
result_id: 2
},
{ 
content: "（兜甲児より分岐）その続編「グレートマジンガー」でグレートマジンガーに乗り込む主人公は？",
result: 0,
sum: 0,
user_id: 1,
select1: "宇門大介",
select2: "流竜馬",
select3: "剣鉄也",
select4: "兜甲児",
result_id: 3
},
{ 
content: "映画「ゴジラVSメカゴジラ」に登場する対ゴジラチームの名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "Gフォース",
select2: "Gアタッカー",
select3: "Gファイター",
select4: "Gグラスパー",
result_id: 1
},
{ 
content: "特撮番組「ウルトラマン80」でウルトラマン80に変身する中学校の教師・矢的猛は何の先生？",
result: 0,
sum: 0,
user_id: 1,
select1: "数学",
select2: "国語",
select3: "体育",
select4: "理科",
result_id: 4
},
{ 
content: "人形劇「サンダーバード」の日本語吹き替え版でレディ・ペネロープ役を演じたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "中村玉緒",
select2: "塩沢とき",
select3: "森光子",
select4: "黒柳徹子",
result_id: 4
},
{ 
content: "漫画家・森真理が「ヤセとメタボのげんき日和」の中でダイエットさせる過程を描いている彼女の夫である漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "長谷川裕一",
select2: "村枝賢一",
select3: "原秀則",
select4: "島本和彦",
result_id: 2
},
{ 
content: "荒木飛呂彦の漫画「スティール・ポール・ラン」で北米大陸横断レースのスタート地点は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ニューヨーク",
select2: "カンザスシティ",
select3: "シカゴ",
select4: "サンディエゴ",
result_id: 4
},
{ 
content: "（サンディエゴより分岐、スティール・ポール・ランで）ゴールはどこ？",
result: 0,
sum: 0,
user_id: 1,
select1: "シカゴ",
select2: "カンザスシティ",
select3: "ニューヨーク",
select4: "サンディエゴ",
result_id: 3
},
{ 
content: "結婚から定年退職までを体験するゲーム「ぼくらのかぞく」の舞台となっている街は？",
result: 0,
sum: 0,
user_id: 1,
select1: "日暮里",
select2: "麻布十番",
select3: "八王子",
select4: "高円寺",
result_id: 4
},
{ 
content: "諸星大二郎の漫画「妖怪ハンター」シリーズの主人公である考古学者の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "飛田礼二郎",
select2: "稗田礼次郎",
select3: "稗田礼次",
select4: "稗田礼二郎",
result_id: 4
},
{ 
content: "漫画「魁クロマティ高校」で1年を牛耳るウラ番・竹之内の弱点といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "機械に弱い",
select2: "胃腸が弱い",
select3: "かわいい女の子に弱い",
select4: "乗り物に弱い",
result_id: 4
},
{ 
content: "なつかしのファミコンゲーム「新人類」で、主人公がパワーアップして変身するプロレスラーといえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "クラッシャー・バンバン・ビガロ",
select2: "アントニオ猪木",
select3: "長州力",
select4: "藤波辰爾",
result_id: 3
},
{ 
content: "トレンドマイクロ社が開発したセキュリティソフト「ウイルスバスター2010」のイメージキャラクタを描いた漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "野中英次",
select2: "西本英雄",
select3: "久米田康治",
select4: "加瀬あつし",
result_id: 2
},
{ 
content: "2010年9月リリースの、globeの15周年記念ベストアルバム「15 YEARS-BEST HIT SELECTION」のジャケットを手がけた漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "高橋陽一",
select2: "原哲夫",
select3: "車田正美",
select4: "北条司",
result_id: 4
},
{ 
content: "漫画「こちら葛飾区亀有公園前派出所」に登場する車の運転が苦手な大学教授は？",
result: 0,
sum: 0,
user_id: 1,
select1: "絵崎獅子丸",
select2: "絵崎O次郎",
select3: "絵崎コロ助",
select4: "絵崎スネ夫",
result_id: 3
},
{ 
content: "ゲーム「サルゲッチュ3」のTVCMに出演したお笑いコンビは？",
result: 0,
sum: 0,
user_id: 1,
select1: "フットボールアワー",
select2: "くりぃむしちゅー",
select3: "インパルス",
select4: "アンガールズ",
result_id: 4
},
{ 
content: "2010年9月から「りぼん」で連載がスタートした漫画「まりもの花～最強武闘派小学生伝説～」の原作を手がけるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "糸井重里",
select2: "リリー・フランキー",
select3: "大槻ケンヂ",
select4: "秋元康",
result_id: 4
},
{ 
content: "TVアニメ「犬夜叉　完結編」のOPテーマ「君がいない未来」を歌った音楽ユニットは？",
result: 0,
sum: 0,
user_id: 1,
select1: "AAA",
select2: "Dream",
select3: "Do As Infinity",
select4: "Every Little Thing",
result_id: 3
},
{ 
content: "（Do As Infinityより分岐、犬夜叉の）初代EDテーマ「With you」を歌った音楽ユニットは？",
result: 0,
sum: 0,
user_id: 1,
select1: "Dream",
select2: "AAA",
select3: "Every Little Thing",
select4: "Do As Infinity",
result_id: 2
},
{ 
content: "ゲーム「デスクリムゾン」の主人公の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "コンバット美作",
select2: "コンバット越前",
select3: "コンバット越後",
select4: "コンバット武蔵",
result_id: 2
},
{ 
content: "アニメ「ご近所物語」で主人公・幸田実果子の声を演じたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "持田真樹",
select2: "松雪泰子",
select3: "宍戸留美",
select4: "内田有紀",
result_id: 3
},
{ 
content: "（宍戸留美より分岐）アニメ「花より男子」で主人公・牧野つくしの声を演じたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "持田真樹",
select2: "内田有紀",
select3: "宍戸留美",
select4: "松雪泰子",
result_id: 1
},
{ 
content: "1985年に「ゲゲゲの鬼太郎」がスペシャルドラマとして実写化されたときにねずみ男を演じた俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "由利徹",
select2: "赤星昇一郎",
select3: "竹中直人",
select4: "佐藤B作",
result_id: 3
},
{ 
content: "（竹中直人より分岐、ゲゲゲの鬼太郎で）砂かけ婆を演じた俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "佐藤B作",
select2: "赤星昇一郎",
select3: "竹中直人",
select4: "由利徹",
result_id: 4
},
{ 
content: "女子高生とその担任の恋を描いた田中メカの漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "5時間目ラプソディー",
select2: "7時間目ラプソディー",
select3: "6時間目ラプソディー",
select4: "4時間目ラプソディー",
result_id: 2
},
{ 
content: "ゲーム機「セガ・サターン」の互換機で、「Hiサターン」を発売した家電メーカーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "日立",
select2: "ビクター",
select3: "NEC",
select4: "東芝",
result_id: 1
},
{ 
content: "レースゲーム「アウトラン」でプレイヤーが搭乗できる車はどのメーカーのもの？",
result: 0,
sum: 0,
user_id: 1,
select1: "アルファロメオ",
select2: "ランボルギーニ",
select3: "フェラーリ",
select4: "ランチャ",
result_id: 3
},
{ 
content: "次のファミコンゲームのうちプレイヤーキャラがジャンプできないのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ヒットラーの復活",
select2: "アトランチスの謎",
select3: "たけしの挑戦状",
select4: "アルゴスの戦士",
result_id: 1
},
{ 
content: "次のうち、1988年放送のアニメ「ハーイあっこです」の主題歌はどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "晴れのち晴れ",
select2: "曇りのち晴れ",
select3: "曇りのち雨",
select4: "晴れのち雨",
result_id: 1
},
{ 
content: "水を好きな食べ物に変える「食べものマシーン」によって起こる騒動を描いた、2009年に公開されたアニメ映画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "くもりときどきビーフステーキ",
select2: "くもりときどきミートボール",
select3: "くもりときどきバーベキュー",
select4: "くもりときどきハンバーグ",
result_id: 2
},
{ 
content: "メガドライブで発売されたゲーム「ソニック・ザ・ヘッジホッグ」の音楽を担当したミュージシャンは？",
result: 0,
sum: 0,
user_id: 1,
select1: "YOSHIKI",
select2: "坂本龍一",
select3: "小室哲哉",
select4: "中村正人",
result_id: 4
},
{ 
content: "少女漫画「桜蘭高校ホスト部」の作者は？",
result: 0,
sum: 0,
user_id: 1,
select1: "葉鳥コロン",
select2: "葉鳥トッポ",
select3: "葉鳥グリコ",
select4: "葉鳥ビスコ",
result_id: 4
},
{ 
content: "代表作に「カブのイサキ」「ヨコハマ買い出し紀行」がある漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "よしづきくみち",
select2: "冬目景",
select3: "鶴田謙二",
select4: "芦奈野ひとし",
result_id: 4
},
{ 
content: "ゲーム「雷電」シリーズによく登場する、恐竜のような形をした隠れキャラクターは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ゴモラ",
select2: "ウィンダム",
select3: "ミクラス",
select4: "ゼットン",
result_id: 3
},
{ 
content: "「ふしぎ魔法ファンファンファーマシィー」など3つの作品が放送されていたアニメ番組の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "アニメ週刊DX！ぷーファみい",
select2: "アニメ週刊DX！ファぷーみい",
select3: "アニメ週刊DX！ファみいぷー",
select4: "アニメ週刊DX！みいファぷー",
result_id: 4
},
{ 
content: "PS用ゲーム「サルゲッチュ」のCMに出演したことがあるタレントは？",
result: 0,
sum: 0,
user_id: 1,
select1: "岡村隆史",
select2: "ゴリ",
select3: "モンキッキー",
select4: "ガッツ石松",
result_id: 4
},
{ 
content: "ゲーム「ブレス　オブ　ファイア」シリーズで、唯一サブタイトルがないのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ブレスオブファイアV",
select2: "ブレスオブファイアIV",
select3: "ブレスオブファイアIII",
select4: "ブレスオブファイアII",
result_id: 3
},
{ 
content: "漫画「BLUE DRAGONラルΩグラド」に登場する犬ヌイの好物は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ポップコーン",
select2: "チーズ",
select3: "ピーナッツ",
select4: "リンゴ",
result_id: 3
},
{ 
content: "アニメ「ドラえもん」でジャイ子の声を演じている女性活弁士は？",
result: 0,
sum: 0,
user_id: 1,
select1: "山崎メロン",
select2: "山崎バナナ",
select3: "山崎バニラ",
select4: "山崎ショコラ",
result_id: 3
},
{ 
content: "アニメ「KAIKANフレーズ」の主題歌に使われたGLAYのヒット曲は？",
result: 0,
sum: 0,
user_id: 1,
select1: "グロリアス",
select2: "口唇",
select3: "サバイバル",
select4: "HOWEVER",
result_id: 3
},
{ 
content: "アニメ「ドクタースランプ」に登場するニコチャン大王が話す言葉はどこの方言？",
result: 0,
sum: 0,
user_id: 1,
select1: "名古屋弁",
select2: "鹿児島弁",
select3: "大阪弁",
select4: "広島弁",
result_id: 1
},
{ 
content: "アニメ「ジャングルの王者ターちゃん」で、主人公ターちゃんの声を演じた俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "西村雅彦",
select2: "石黒賢",
select3: "岸谷五朗",
select4: "唐沢寿明",
result_id: 3
},
{ 
content: "カービィやヨッシーなど任天堂のキャラクターが登場するゼルダシリーズの異色作は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ゼルダの伝説夢をみる島",
select2: "ゼルダの伝説風のタクト",
select3: "ゼルダの伝説不思議の木のミ",
select4: "ゼルダの伝説時のオカリナ",
result_id: 1
},
{ 
content: "2003年放送のTVアニメ「出撃！マシンロボレスキュー」に登場する携帯電話型のロボットといえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "D-BOY",
select2: "K-BOY",
select3: "P-BOY",
select4: "T-BOY",
result_id: 2
},
{ 
content: "2010年10月にロックバンドGLAYがリリースしたアルバム「GLAY」に収録された短編アニメ「Je t'aime」を手がけたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "新海誠",
select2: "原恵一",
select3: "織田守",
select4: "押井守",
result_id: 4
},
{ 
content: "漫画「あしたのジョー」に登場するカーロス・リベラはどこの国出身のボクサー？",
result: 0,
sum: 0,
user_id: 1,
select1: "ベネズエラ",
select2: "メキシコ",
select3: "コロンビア",
select4: "エクアドル",
result_id: 1
},
{ 
content: "漫画「代紋　TAKE2」で主人公の丈二がタイムスリップして結婚した女性は？",
result: 0,
sum: 0,
user_id: 1,
select1: "奈々子",
select2: "美穂子",
select3: "カオリ",
select4: "美也子",
result_id: 3
},
{ 
content: "（カオリより分岐、代紋で主人公の丈二が）タイムスリップする前に結婚した女性は？",
result: 0,
sum: 0,
user_id: 1,
select1: "カオリ",
select2: "奈々子",
select3: "美也子",
select4: "美穂子",
result_id: 3
},
{ 
content: "セガの格闘ゲーム「バーチャファイター」で結城晶が使う拳法は？",
result: 0,
sum: 0,
user_id: 1,
select1: "八極拳",
select2: "蟷螂拳",
select3: "虎燕拳",
select4: "酔拳",
result_id: 1
},
{ 
content: "（八極拳より分岐、バーチャで）ラウ・チェンが使う拳法は？",
result: 0,
sum: 0,
user_id: 1,
select1: "虎燕拳",
select2: "八極拳",
select3: "蟷螂拳",
select4: "酔拳",
result_id: 1
},
{ 
content: "2009年9月に特番として放送されるアニメ「ジャングル大帝」で、レオの父親パンジャの声を演じる俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "陣内孝則",
select2: "堤真一",
select3: "中井貴一",
select4: "時任三郎",
result_id: 4
},
{ 
content: "アメリカのキャラクター、ウッディ・ウッドペッカーはどんな動物？",
result: 0,
sum: 0,
user_id: 1,
select1: "キツツキ",
select2: "カモ",
select3: "カナリヤ",
select4: "ペリカン",
result_id: 1
},
{ 
content: "「ワールドサッカーウイニングイレブン７インターナショナル」の「プレミアムパッケージ」でコナミとコラボレートしたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ルコック",
select2: "プーマ",
select3: "ロイシュ",
select4: "アディダス",
result_id: 4
},
{ 
content: "2004年公開の映画「ゴジラFINAL WARS」で万能戦艦・轟天号の艦長ゴードンを演じた格闘家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ミルコ・クロコップ",
select2: "ドン・フライ",
select3: "ボブ・サップ",
select4: "ヴァンダレイ・シウバ",
result_id: 2
},
{ 
content: "PS2用のクイズゲームで「アメリカ横断ウルトラクイズ」を発売したメーカーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "デジキューブ",
select2: "アイドス",
select3: "コナミ",
select4: "ハドソン",
result_id: 1
},
{ 
content: "（デジキューブより分岐）「オールスター感謝祭」を発売したメーカーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "アイドス",
select2: "コナミ",
select3: "ハドソン",
select4: "デジキューブ",
result_id: 3
},
{ 
content: "押井守や荒牧伸志らも参加してアニメ化されることになったXbox用ゲームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "Perfect Dark Zero",
select2: "RIOT ACT",
select3: "Gears of War",
select4: "Halo",
result_id: 4
},
{ 
content: "「三国志」が題材のオンラインゲーム「キャラクター大作戦」でプレイヤーキャラクターとして登場しているミュージシャンは？",
result: 0,
sum: 0,
user_id: 1,
select1: "GACKT",
select2: "hyde",
select3: "DAIGO",
select4: "YOSHIKI",
result_id: 4
},
{ 
content: "1993年にSNKがネオジオで発売したプロレスゲームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ファイヤースープレックス",
select2: "ファイヤーライアート",
select3: "ファイヤーヘッドロック",
select4: "ファイヤードライバー",
result_id: 1
},
{ 
content: "1992年に放送された真田十勇士をモチーフにしたTVアニメは？",
result: 0,
sum: 0,
user_id: 1,
select1: "サラダ十勇士レタスマン",
select2: "サラダ十勇士トマトマン",
select3: "サラダ十勇士ポテトマン",
select4: "サラダ十勇士ピーマン",
result_id: 2
},
{ 
content: "アニメ「ミスター味っ子」に登場する料理人で「ミスター味っ子」と呼ばれるのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "味吉陽一",
select2: "村田源二郎",
select3: "中江兵太",
select4: "堺一馬",
result_id: 1
},
{ 
content: "（味吉陽一より分岐、ミスター味っ子で）「素材の魔術師」と呼ばれるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "中江兵太",
select2: "味吉陽一",
select3: "村田源二郎",
select4: "堺一馬",
result_id: 1
},
{ 
content: "「新世紀エヴァンゲリオン」や「北斗の拳」のアクションフィギュアを発売している玩具メーカーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "浪漫堂",
select2: "メガハウス",
select3: "海洋堂",
select4: "メディコム・トイ",
result_id: 3
},
{ 
content: "1981年放映開始のTVアニメ「じゃりん子チエ」で主人公の父親・竹本テツの声を担当したお笑い芸人は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ぼんちおさむ",
select2: "西川のりお",
select3: "明石家さんま",
select4: "横山やすし",
result_id: 2
},
{ 
content: "2009年11月に発売されるWii用ゲーム「戦国無双3」のエンディング曲を担当するミュージシャンは？",
result: 0,
sum: 0,
user_id: 1,
select1: "DAIGO",
select2: "hyde",
select3: "GACKT",
select4: "KREVA",
result_id: 3
},
{ 
content: "特撮番組「ウルトラマン」でウルトラマンが地球に来て最初に倒したのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ネロンガ",
select2: "バルタン星人",
select3: "クール星人",
select4: "ベムラー",
result_id: 4
},
{ 
content: "（ベムラーより分岐、ウルトラマンが）2番目に倒したのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ネロンガ",
select2: "バルタン星人",
select3: "クール星人",
select4: "ベムラー",
result_id: 2
},
{ 
content: "アニメ「絶対無敵ライジンオー」で、巨大ロボ・ライジンオーで地球を守る地球防衛組は陽昇学園の何年何組？",
result: 0,
sum: 0,
user_id: 1,
select1: "4年4組",
select2: "4年3組",
select3: "5年4組",
select4: "5年3組",
result_id: 4
},
{ 
content: "アニメ「まじかるカナン」で主人公の柊ちはやが変身するのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "セルリアンブルー",
select2: "ナツキ",
select3: "カーマイン",
select4: "セプティム",
result_id: 3
},
{ 
content: "（カーマインより分岐、まじかるカナンで）水樹さやかが変身するのは何という魔法戦士？",
result: 0,
sum: 0,
user_id: 1,
select1: "ナツキ",
select2: "セプティム",
select3: "カーマイン",
select4: "セルリアンブルー",
result_id: 4
},
{ 
content: "RPG「ゼノサーガエピソードＩ」のサブタイトルといえば何？",
result: 0,
sum: 0,
user_id: 1,
select1: "悦ばしき知識",
select2: "永劫回帰",
select3: "善悪の彼岸",
select4: "力への意思",
result_id: 4
},
{ 
content: "（力への意思より分岐）その続編である「ゼノサーガエピソードＩＩ」のサブタイトルといえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "永劫回帰",
select2: "善悪の彼岸",
select3: "力への意思",
select4: "悦ばしき知識",
result_id: 2
},
{ 
content: "漫画「エロイカより愛をこめて」に登場するエーベルバッハ大佐の過去を描いた作品といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "椿姫",
select2: "スペードの女王",
select3: "魔弾の射手",
select4: "ローエングリン",
result_id: 3
},
{ 
content: "ゲーム「ひぐらしのなく頃に」の漫画版で、「鬼隠し編」が連載された雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "月刊ガンガンＷＩＮＧ",
select2: "月刊Ｇファンタジー",
select3: "ガンガンパワード",
select4: "月刊少年ガンガン",
result_id: 3
},
{ 
content: "漫画「ガラスの仮面」で北島マヤが舞台「ぶたりの王女」のオーディションで使った当時のヒット曲は？",
result: 0,
sum: 0,
user_id: 1,
select1: "キッスは目にして",
select2: "メモリー・グラス",
select3: "失恋レストラン",
select4: "夜霧のハウスマヌカン",
result_id: 1
},
{ 
content: "漫画「るろうに剣心」の主人公のモデルになった人斬りは？",
result: 0,
sum: 0,
user_id: 1,
select1: "桐野利秋",
select2: "岡田以蔵",
select3: "伊藤俊輔",
select4: "河上彦斎",
result_id: 4
},
{ 
content: "タツノコプロのTVアニメで紀里谷和明監督によって2003年に実写映画化されたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "科学忍者隊ガッチャマン",
select2: "ヤッターマン",
select3: "新造人間キャシャーン",
select4: "マッハGoGoGo",
result_id: 3
},
{ 
content: "（新造人間キャシャーンより分岐）2008年にウォシャウスキー兄弟によってハリウッド実写映画化されたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "科学忍者隊ガッチャマン",
select2: "マッハGoGoGo",
select3: "ヤッターマン",
select4: "新造人間キャシャーン",
result_id: 2
},
{ 
content: "異世界に迷い込んだ夕城美朱が彼女を守る朱雀七星士たちと聖獣を呼び出すための旅をする渡瀬悠宇のファンタジー漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "日帰りクエスト",
select2: "ふしぎ遊戯",
select3: "フィーメンニンは謳う",
select4: "神無月の巫女",
result_id: 2
},
{ 
content: "劇場版「仮面ライダーカブト」で仮面ライダーコーカサスの変身前を演じた格闘家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "武蔵",
select2: "佐竹雅昭",
select3: "角田信朗",
select4: "魔裟斗",
result_id: 1
},
{ 
content: "2009年公開のアニメ映画「ナットのスペースアドベンチャー」でアポロ11号で宇宙に行った主人公ナットはどんな昆虫？",
result: 0,
sum: 0,
user_id: 1,
select1: "ハエ",
select2: "カブトムシ",
select3: "チョウ",
select4: "トンボ",
result_id: 1
},
{ 
content: "浦沢直樹の漫画「PLUTO」の冒頭で破壊されてしまうスイスのロボットは？",
result: 0,
sum: 0,
user_id: 1,
select1: "アルプス",
select2: "マッターホルン",
select3: "グランドジョラス",
select4: "モンブラン",
result_id: 4
},
{ 
content: "ゲーム「北へ。～Diamond Dust～」で茜木温子が住む北海道の都市は？",
result: 0,
sum: 0,
user_id: 1,
select1: "函館の写真",
select2: "富良野の写真",
select3: "稚内の写真",
select4: "札幌の写真",
result_id: 1
},
{ 
content: "漫画「課長島耕作」シリーズで初芝電産に入社した島耕作が配属された部署はどこ？",
result: 0,
sum: 0,
user_id: 1,
select1: "総務課",
select2: "経理課",
select3: "商品開発課",
select4: "広告課",
result_id: 4
},
{ 
content: "モノクロ版「怪物くん」で毎回番組の最後で、解説を担当していた映画評論家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "浜村淳",
select2: "小森和子",
select3: "水野晴郎",
select4: "淀川長治",
result_id: 4
},
{ 
content: "特撮番組「宇宙刑事ギャバン」に登場する、ギャバンの相棒の女性の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ダイアナ",
select2: "リリィ",
select3: "アニー",
select4: "ミミー",
result_id: 4
},
{ 
content: "２００９年９月から放送の特撮番組「仮面ライダーＷ」で刑事の刃野幹夫を演じるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "宇治原史規",
select2: "なだぎ武",
select3: "宮川大輔",
select4: "なすび",
result_id: 2
},
{ 
content: "（両津のラサール石井より分岐）「レレレの天才バカボン」でバカボンのパパの声を演じたタレントは？",
result: 0,
sum: 0,
user_id: 1,
select1: "出川哲朗",
select2: "ラサール石井",
select3: "上島竜平",
select4: "小倉久寛",
result_id: 4
},
{ 
content: "岡野玲子の漫画「ファンシィダンス」で主人公の陽平が目指す職業は？",
result: 0,
sum: 0,
user_id: 1,
select1: "陰陽師",
select2: "僧侶",
select3: "仙人",
select4: "役人",
result_id: 2
},
{ 
content: "（僧侶より分岐）同じく岡野玲子の漫画「妖魅変成夜話」で主人公の李成澤が就いた職業は？",
result: 0,
sum: 0,
user_id: 1,
select1: "役人",
select2: "陰陽師",
select3: "僧侶",
select4: "仙人",
result_id: 1
},
{ 
content: "2009年8月に小学館が創刊した月刊の漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "月刊！オリジナル",
select2: "月刊！スピリッツ",
select3: "月刊！スペリオール",
select4: "月刊！ビッグコミック",
result_id: 2
},
{ 
content: "結婚から定年退職までを体験するゲーム「ぼくらのかぞく」の舞台となっている街は？",
result: 0,
sum: 0,
user_id: 1,
select1: "高円寺",
select2: "麻布十番",
select3: "日暮里",
select4: "八王子",
result_id: 1
},
{ 
content: "正義の戦士と悪の組織の日常を描いたくぼたまことの漫画「天体戦士サンレッド」の舞台となっている神奈川県の都市は？",
result: 0,
sum: 0,
user_id: 1,
select1: "平塚市",
select2: "川崎市",
select3: "相模原市",
select4: "鎌倉市",
result_id: 2
},
{ 
content: "「愛・地球博」のマスコットキャラクターを主役にしたアニメ「モリゾーとキッコロの休日」の監督は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "宮崎駿",
select2: "押井守",
select3: "高橋良輔",
select4: "庵野秀明",
result_id: 3
},
{ 
content: "映画「風の谷のナウシカ」のイメージソングを歌った当時のアイドルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "安田成美",
select2: "山瀬まみ",
select3: "統乃さゆみ",
select4: "立花理佐",
result_id: 1
},
{ 
content: "（安田成美より分岐）映画「王立宇宙軍オネアミスの翼」のイメージソングを歌った当時のアイドルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "統乃さゆみ",
select2: "立花理佐",
select3: "安田成美",
select4: "山瀬まみ",
result_id: 1
},
{ 
content: "1982年に日本テレビの特番「24時間テレビ」内でアニメ化された竹宮恵子の漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "アンドロメダ・ストーリーズ",
select2: "地球へ…",
select3: "風と木の詩",
select4: "夏への扉",
result_id: 1
},
{ 
content: "2009年に、香港・フランス共同製作映画として実写映画化された、日本のProduction IGが生んだアニメは？",
result: 0,
sum: 0,
user_id: 1,
select1: "攻殻機動隊",
select2: "LAST EXILE",
select3: "SPEED GRAPHER",
select4: "BLOOD THE LAST VANPIRE",
result_id: 4
},
{ 
content: "アニメ「おじゃる丸」に登場するカズマのクラスメートのナルシストな女の子といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "小野小町",
select2: "清少納言",
select3: "紫式部",
select4: "和泉式部",
result_id: 1
},
{ 
content: "アニメ「ふしぎ星の☆ふたご姫」で、ファインとレインは何の国のプリンセス？",
result: 0,
sum: 0,
user_id: 1,
select1: "しずくの国",
select2: "メラメラの国",
select3: "おひさまの国",
select4: "宝石の国",
result_id: 3
},
{ 
content: "（おひさまの国より分岐、ふしぎ星の☆ふたご姫で）アルテッサはどこの国のプリンセス？",
result: 0,
sum: 0,
user_id: 1,
select1: "宝石の国",
select2: "しずくの国",
select3: "メラメラの国",
select4: "おひさまの国",
result_id: 1
},
{ 
content: "自分の前世の幽霊に寿命を告げられた刑事を主人公とする山本康人の漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "超人アムロ",
select2: "超人ウタダ",
select3: "超人クラキ",
select4: "超人ハマサキ",
result_id: 2
},
{ 
content: "2009年7月発売のゲーム「ぷよぷよ７」の主人公は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ないとうみかん",
select2: "えんどうすいか",
select3: "さいとうめろん",
select4: "あんどうりんご",
result_id: 4
},
{ 
content: "漫画「巨人の星」で巨人軍に入団した星飛雄馬がつけた背番号は、どの永久欠番？",
result: 0,
sum: 0,
user_id: 1,
select1: "沢村栄治の１４",
select2: "金田正一の３４",
select3: "川上哲治の１６",
select4: "黒沢俊夫の４",
result_id: 3
},
{ 
content: "漫画「銀河鉄道999」が連載されていた漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊少年サンデー",
select2: "週刊少年キング",
select3: "週刊少年チャンピオン",
select4: "週刊少年マガジン",
result_id: 2
},
{ 
content: "特撮番組「仮面ライダー響鬼」第1話で、安達明日夢がヒビキと出会ったのはどこに向かう船の上？",
result: 0,
sum: 0,
user_id: 1,
select1: "波照間島",
select2: "屋久島",
select3: "奄美大島",
select4: "種子島",
result_id: 2
},
{ 
content: "アニメ「じゃりん子チエ」でチエちゃんが仕切っている実家のお店は？",
result: 0,
sum: 0,
user_id: 1,
select1: "お好み焼き屋",
select2: "クレープ屋",
select3: "ラーメン屋",
select4: "ホルモン焼き屋",
result_id: 4
},
{ 
content: "1963年に放送を開始した国産初の30分TVアニメシリーズは？",
result: 0,
sum: 0,
user_id: 1,
select1: "魔法使いサリー",
select2: "鉄人28号",
select3: "鉄腕アトム",
select4: "ジャングル大帝",
result_id: 3
},
{ 
content: "次のうち、広島県廿日市市が発祥ともいわれるおもちゃはどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "コマの写真",
select2: "けんだまの写真",
select3: "ヨーヨーの写真",
select4: "？？？の写真",
result_id: 2
},
{ 
content: "1978年公開の映画「ルパン三世ルパンｖｓ複製人間」でマモーの声を演じた水戸黄門役でおなじみの俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "西村晃",
select2: "東野英治郎",
select3: "里見浩太朗",
select4: "佐野浅夫",
result_id: 1
},
{ 
content: "ゲームに登場する女の子が通う学校の校歌を集めたCDを発売された恋愛ゲームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ToHeart",
select2: "トゥルー・ラブストーリー",
select3: "ときめきメモリアル",
select4: "センチメンタルグラフティ",
result_id: 4
},
{ 
content: "アニメ「獣神ライガー」でライガーは善の絶対神の化身ですが、その神の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ウィルゲム",
select2: "ピースミリオン",
select3: "アーガマ",
select4: "ラー・カイラム",
result_id: 3
},
{ 
content: "漫画「封神演義」の舞台となっている古代中国の王朝は？",
result: 0,
sum: 0,
user_id: 1,
select1: "夏",
select2: "秦",
select3: "漢",
select4: "殷",
result_id: 4
},
{ 
content: "雑誌「週刊マンガ日本史」の創刊号で、卑弥呼を題材とした漫画を手がけた漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "藤原カムイ",
select2: "大島やすいち",
select3: "山田貴敏",
select4: "安彦良和",
result_id: 1
},
{ 
content: "12月公開の映画「大怪獣バトルウルトラ銀河伝説」でレイブラッド星人の声を演じるプロレスラーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "蝶野正洋",
select2: "武藤敬司",
select3: "小橋健太",
select4: "佐々木健介",
result_id: 1
},
{ 
content: "女の子に大ヒットしたゲーム「オシャレ魔女ラブandベリー」の主人公ラブとベリーはともに何歳？",
result: 0,
sum: 0,
user_id: 1,
select1: "17歳",
select2: "14歳",
select3: "16歳",
select4: "15歳",
result_id: 2
},
{ 
content: "旧ソ連時代のバレエ学校を舞台に泣き虫バレリーナ・ノンナ・ペドロワの姿を描いた山岸涼子のバレエ漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "テレプシコーラ",
select2: "SWAN",
select3: "昴",
select4: "アラベスク",
result_id: 4
},
{ 
content: "ゲーム「J LEAGUE　プロサッカークラブをつくろう！６」でライバルクラブの監督として登場する人物は？",
result: 0,
sum: 0,
user_id: 1,
select1: "加茂周",
select2: "ラモス瑠偉",
select3: "松木安太郎",
select4: "柱谷哲治",
result_id: 2
},
{ 
content: "アニメ「ザ・ウルトラマン」に登場する、ウルトラマンジョーニアスの故郷は？",
result: 0,
sum: 0,
user_id: 1,
select1: "U40",
select2: "G40",
select3: "X40",
select4: "M40",
result_id: 1
},
{ 
content: "2009年10月に、初の本人名義のシングル曲「love your life」をリリースした人気声優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "豊崎愛生",
select2: "戸松遥",
select3: "高垣彩陽",
select4: "寿美菜子",
result_id: 1
},
{ 
content: "アクションゲーム「メタルスラッグ」のプレイヤーキャラクターにいるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "マルコ・ロッシ",
select2: "トム・ソーヤ",
select3: "ネロ・ダース",
select4: "スターリング・ノース",
result_id: 1
},
{ 
content: "クエンティン・タランティーノ監督の映画「キル・ビル」のアニメパートを手がけた日本のアニメ製作会社は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ガイナックス",
select2: "プロダクションIG",
select3: "スタジオジブリ",
select4: "サンライズ",
result_id: 2
},
{ 
content: "アニメ「超獣機神ダンクーガ」の主題歌を歌った元アイドルでのちにCCガールズのメンバーとしても活躍したのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "青田典子",
select2: "藤原理恵",
select3: "藤森夕子",
select4: "原田徳子",
result_id: 2
},
{ 
content: "AUDIO RULEZが歌うアニメ「ジパング」の主題歌の題名は？",
result: 0,
sum: 0,
user_id: 1,
select1: "活版印刷術",
select2: "火薬",
select3: "製紙法",
select4: "羅針盤",
result_id: 4
},
{ 
content: "次のうちかつて「ジャンプ放送局」のアシスタントを務めたことがある漫画化は？",
result: 0,
sum: 0,
user_id: 1,
select1: "柴田亜美",
select2: "みずしな孝之",
select3: "鈴木みそ",
select4: "近藤るるる",
result_id: 3
},
{ 
content: "おまけ付きお菓子「ビックリマンチョコ」を発売したお菓子メーカーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ロッテ",
select2: "森永製菓",
select3: "カルビー",
select4: "明治製菓",
result_id: 1
},
{ 
content: "（ロッテより分岐）「仰天人間バトシーラー」を発売したお菓子メーカーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "森永製菓",
select2: "明治製菓",
select3: "ロッテ",
select4: "カルビー",
result_id: 2
},
{ 
content: "洋画の吹き替えでおなじみの声優で、映画「Mr BOO！」のマイケル・ホイの声といえば誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "内海賢二",
select2: "玄田哲章",
select3: "山田康雄",
select4: "広川太一郎",
result_id: 4
},
{ 
content: "（広川太一郎より分岐、洋画の吹き替えで）ジャック・ニコルソンの声といえば誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "玄田哲章",
select2: "山田康雄",
select3: "内海賢二",
select4: "広川太一郎",
result_id: 3
},
{ 
content: "映画「トランスフォーマー・ザ・ムービー」のユニクロン役が遺作となった有名な俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "マーロン・ブランド",
select2: "ジャック・レモン",
select3: "グレゴリー・ペック",
select4: "オーソン・ウェルズ",
result_id: 4
},
{ 
content: "2008年に乙黒えり、中村知世らの主演により実写映画化されたゲームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "デッドオアアライブ",
select2: "メルティブラッド",
select3: "アルカナハート",
select4: "お姉チャンバラ",
result_id: 4
},
{ 
content: "史上始めてオープニング主題歌がついたRPG「コズミックファンタジー　冒険少年ユウ」で主題歌を歌ったアイドルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "西田ひかる",
select2: "酒井法子",
select3: "島崎和歌子",
select4: "西村知美",
result_id: 4
},
{ 
content: "「レッスルエンジェルス」の携帯電話用ゲームの題名は「レッスルエンジェルス何」？",
result: 0,
sum: 0,
user_id: 1,
select1: "打",
select2: "軽",
select3: "闘",
select4: "愛",
result_id: 4
},
{ 
content: "テレビ東京で放送されたTVアニメのうち歴代最高視聴率を記録したのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "新世紀エヴァンゲリオン",
select2: "まいっちんぐマチコ先生",
select3: "キャプテン翼",
select4: "ポケットモンスター",
result_id: 3
},
{ 
content: "ゲーム「パンツァーフロント」の舞台となっている戦争は？",
result: 0,
sum: 0,
user_id: 1,
select1: "日露戦争",
select2: "第一次世界大戦",
select3: "第二次世界大戦",
select4: "日清戦争",
result_id: 3
},
{ 
content: "特撮番組「ウルトラQ」の最終回「あけてくれ！」を担当したベテラン脚本家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "小山内美江子",
select2: "内館牧子",
select3: "鎌田敏夫",
select4: "倉本聰",
result_id: 1
},
{ 
content: "アニメ「ゲゲゲの鬼太郎」の脚本を手がけたこともある直木賞作家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "石田衣良",
select2: "京極夏彦",
select3: "朱川湊人",
select4: "重松清",
result_id: 2
},
{ 
content: "ガンダムのプラモデルを生産する「バンダイホビーセンター」がある都市は？",
result: 0,
sum: 0,
user_id: 1,
select1: "仙台市",
select2: "岡山市",
select3: "大阪市",
select4: "静岡市",
result_id: 4
},
{ 
content: "「仮面ライダー電王」などの平成「仮面ライダー」シリーズがタイアップしたCMが話題のドリンクは？",
result: 0,
sum: 0,
user_id: 1,
select1: "リポビタンD",
select2: "オロナミンC",
select3: "リアルゴールド",
select4: "CCレモン",
result_id: 2
},
{ 
content: "特撮番組「超人バロム・１」でバロム・１が乗るマシンは？",
result: 0,
sum: 0,
user_id: 1,
select1: "マッハロッド",
select2: "ライジンゴー",
select3: "ハヤブサオー",
select4: "ドルフィン",
result_id: 1
},
{ 
content: "（マッハロッドより分岐）「星雲仮面マシンマン」でマシンマンが乗るマシンは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ライジンゴー",
select2: "ハヤブサオー",
select3: "マッハロッド",
select4: "ドルフィン",
result_id: 4
},
{ 
content: "「月刊アフタヌーン」で連載されているハグキのギャグマンガは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ハトのおよめさん",
select2: "ハトのおばあさん",
select3: "ハトのおむこさん",
select4: "ハトのおじいさん",
result_id: 1
},
{ 
content: "漫画「MASTERキートン」で主人公の考古学者平賀・キートン・太一が卒業した大学は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ケンブリッジ大学",
select2: "オックスフォード大学",
select3: "ハーバード大学",
select4: "エール大学",
result_id: 2
},
{ 
content: "2011年に佐藤竜雄監督によってアニメ化されることが決まった笹本祐一の小説は？",
result: 0,
sum: 0,
user_id: 1,
select1: "セーラー宇宙海賊",
select2: "ミニスカ宇宙海賊",
select3: "ノーブラ宇宙海賊",
select4: "パンチラ宇宙海賊",
result_id: 2
},
{ 
content: "アニメ「ダーティペア」でユリの声を演じた声優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "頓宮恭子",
select2: "國府田マリ子",
select3: "松本梨香",
select4: "島津冴子",
result_id: 4
},
{ 
content: "（島津冴子より分岐、ダーティペアで）ケイの声を演じた声優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "島津冴子",
select2: "國府田マリ子",
select3: "頓宮恭子",
select4: "松本梨香",
result_id: 3
},
{ 
content: "漫画「20世紀少年」で「ともだち」のマークを考案したのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "サダキヨ",
select2: "フクベエ",
select3: "ドンキー",
select4: "オッチョ",
result_id: 4
},
{ 
content: "古谷徹、銀河万丈、金田朋子らが所属する声優事務所といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "青二プロダクション",
select2: "大沢事務所",
select3: "テアトル・エコー",
select4: "賢プロダクション",
result_id: 1
},
{ 
content: "アニメ「キン肉マンII世」の主題歌を歌った歌手・河野陽吾がかつてキーボードを担当していたバンドは？",
result: 0,
sum: 0,
user_id: 1,
select1: "EARTHSHAKER",
select2: "HUMMING BIRD",
select3: "レイジー",
select4: "MAKE-UP",
result_id: 4
},
{ 
content: "アニメ「トランスフォーマーギャラクシーフォース」でフォースチップを使うときに叫ぶ決めゼリフは？",
result: 0,
sum: 0,
user_id: 1,
select1: "プロダクション",
select2: "イグニッション",
select3: "エボリューション",
select4: "コレクション",
result_id: 2
},
{ 
content: "アニメ「ダーティペア」の主題歌「ロ・ロ・ロ・ロシアンルーレット」を歌った歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "中原めいこ",
select2: "結城めぐみ",
select3: "馬渡松子",
select4: "鮎川麻弥",
result_id: 1
},
{ 
content: "ミヒャエル・エンデのファンタジー小説「終わらない物語」に登場するドラゴンの名は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ファルコン",
select2: "ファミコン",
select3: "ファルゴン",
select4: "フェミゴン",
result_id: 1
},
{ 
content: "永井豪の漫画「デビルマン」が連載された漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊少年マガジン",
select2: "週刊少年ジャンプ",
select3: "週刊少年チャンピオン",
select4: "週刊少年サンデー",
result_id: 1
},
{ 
content: "（週刊少年マガジンより分岐、永井豪の漫画で）「マジンガーZ」が連載された漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊少年サンデー",
select2: "週刊少年ジャンプ",
select3: "週刊少年チャンピオン",
select4: "週刊少年マガジン",
result_id: 2
},
{ 
content: "2009年に公開されたアニメ映画「プリキュアオールスターズDX」で、登場したプリキュアオールスターズは全部で何人？",
result: 0,
sum: 0,
user_id: 1,
select1: "14人",
select2: "15人",
select3: "13人",
select4: "16人",
result_id: 1
},
{ 
content: "2005年放送のアニメ「ガンソード」に登場する情報屋の美女といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "カルメン99",
select2: "カルメン88",
select3: "カルメン66",
select4: "カルメン77",
result_id: 1
},
{ 
content: "ファミコンゲーム「ボンバーマン」の隠れキャラとして登場する、当時のハドソンのプログラマーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "松本さん",
select2: "藤本さん",
select3: "橋本さん",
select4: "中本さん",
result_id: 4
},
{ 
content: "那州雪絵の少女漫画「ここはグリーン・ウッド」の舞台となる男子寮は？",
result: 0,
sum: 0,
user_id: 1,
select1: "緑森寮",
select2: "緑木寮",
select3: "森木寮",
select4: "緑林寮",
result_id: 4
},
{ 
content: "ホビー専門誌「電撃ホビーマガジン」を発行している出版社は？",
result: 0,
sum: 0,
user_id: 1,
select1: "徳間書店",
select2: "ワールドフォトプレス",
select3: "アスキー・メディアワークス",
select4: "竹書房",
result_id: 3
},
{ 
content: "（アスキー・メディアワークスより分岐、ホビー専門誌）「ハイパーホビー」を発行している出版社は？",
result: 0,
sum: 0,
user_id: 1,
select1: "徳間書店",
select2: "竹書房",
select3: "ワールドフォトプレス",
select4: "アスキー・メディアワークス",
result_id: 1
},
{ 
content: "映画「銀河鉄道999」で時間城で鉄郎を守って爆死する盗賊の名前は？",
result: 0,
sum: 0,
user_id: 1,
select1: "シリウス",
select2: "アンタレス",
select3: "カノープス",
select4: "アルデバラン",
result_id: 2
},
{ 
content: "桑原水菜の小説「炎の蜃気楼」シリーズで、主人公の仰木高耶は誰の生まれ変わり？",
result: 0,
sum: 0,
user_id: 1,
select1: "上杉景虎",
select2: "北条氏直",
select3: "今川範以",
select4: "武田勝頼",
result_id: 1
},
{ 
content: "漫画「カードキャプターさくら」で、さくらの友達の大道寺知世が大好きなTVドラマは何？",
result: 0,
sum: 0,
user_id: 1,
select1: "踊る大捜査線",
select2: "はぐれ刑事純情派",
select3: "あぶない刑事",
select4: "古畑任三郎",
result_id: 2
},
{ 
content: "タレントの照英が俳優としてのデビューを飾った特撮番組は？",
result: 0,
sum: 0,
user_id: 1,
select1: "激走戦隊カーレンジャー",
select2: "星獣戦隊ギンガマン",
select3: "救急戦隊ゴーゴーファイブ",
select4: "電磁戦隊メガレンジャー",
result_id: 2
},
{ 
content: "シューティングゲーム「超兄貴」のPS版のサブタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "筋肉宇宙昇天素敵男",
select2: "最強究極無敵銀河男",
select3: "究極無敵銀河最強男",
select4: "無敵最強銀河究極男",
result_id: 3
},
{ 
content: "漫画「魁！！男塾」に登場するアメリカ人ボクサーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "J",
select2: "F",
select3: "K",
select4: "G",
result_id: 1
},
{ 
content: "漫画「ブラック・ジャック」でブラック・ジャックが得意とするのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ボウリングの写真",
select2: "卓球の写真",
select3: "ダーツの写真",
select4: "ビリヤードの写真",
result_id: 3
},
{ 
content: "アニメ「北斗の拳」の主題歌「愛をとりもどせ！！」を歌ったのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "TMRevolution",
select2: "TOM★CAT",
select3: "TM NETWORK",
select4: "クリスタルキング",
result_id: 4
},
{ 
content: "（クリスタルキングより分岐）アニメ「北斗の拳2」の主題歌「TOUGH BOY」を歌ったのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "TM NETWORK",
select2: "クリスタルキング",
select3: "TMRevolution",
select4: "TOM★CAT",
result_id: 4
},
{ 
content: "どんな願いでもかなうという宝石が胸に埋め込まれている中学生・姫乃を主人公とした新條まゆの漫画は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ハートのダイヤ",
select2: "ダイヤのクラブ",
select3: "クラブのスペード",
select4: "スペードのハート",
result_id: 1
},
{ 
content: "アニメ「ふたりはプリキュア」のオープニングテーマを歌った女性歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "五篠真由美",
select2: "工藤真由",
select3: "うちやえゆか",
select4: "宮本佳那子",
result_id: 1
},
{ 
content: "（五篠真由美より分岐）「ふたりはプリキュアSplash Star」のオープニングテーマを歌った女性歌手は？",
result: 0,
sum: 0,
user_id: 1,
select1: "五篠真由美",
select2: "宮本佳那子",
select3: "うちやえゆか",
select4: "工藤真由",
result_id: 3
},
{ 
content: "2007年に放送された特撮番組「美少女戦闘舞パンシャーヌ」でパンシャーヌを演じたグラビアアイドルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "山崎真実",
select2: "矢吹春奈",
select3: "原幹恵",
select4: "秋山莉奈",
result_id: 2
},
{ 
content: "漫画「天は赤い河のほとり」で主人公・ユーリがタイムスリップした古代の国は？",
result: 0,
sum: 0,
user_id: 1,
select1: "カッシート",
select2: "バビロニア",
select3: "アッシリア",
select4: "ヒッタイト",
result_id: 4
},
{ 
content: "ナムコの格闘ゲーム「鉄拳」シリーズに登場するキャラでロジャーといえばどんな動物？",
result: 0,
sum: 0,
user_id: 1,
select1: "カンガルー",
select2: "パンダ",
select3: "恐竜",
select4: "クマ",
result_id: 1
},
{ 
content: "（カンガルーより分岐、鉄拳で）アレックスといえばどんな動物？",
result: 0,
sum: 0,
user_id: 1,
select1: "パンダ",
select2: "カンガルー",
select3: "恐竜",
select4: "クマ",
result_id: 3
},
{ 
content: "アニメ「機動戦士ガンダム」でRX-78ガンダムをデザインしたメカデザイナーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "藤田一己",
select2: "出渕裕",
select3: "カトキハジメ",
select4: "大河原邦男",
result_id: 4
},
{ 
content: "（大河原邦男より分岐）「機動警察パトレイバー」でパトレイバーをデザインしたメカデザイナーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "カトキハジメ",
select2: "藤田一己",
select3: "出渕裕",
select4: "大河原邦男",
result_id: 3
},
{ 
content: "漫画「リングにかけろ」でギャラクティカ・マグナムといえば、誰の必殺ブロー？",
result: 0,
sum: 0,
user_id: 1,
select1: "剣崎順",
select2: "高嶺竜児",
select3: "香取石松",
select4: "河井武士",
result_id: 1
},
{ 
content: "（剣崎順より分岐、リングにかけろで）ジェット・アッパーといえば誰の必殺ブロー？",
result: 0,
sum: 0,
user_id: 1,
select1: "香取石松",
select2: "河井武士",
select3: "高嶺竜児",
select4: "剣崎順",
result_id: 2
},
{ 
content: "特撮番組「仮面ライダーアギト」で、仮面ライダーアギトに変身するのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "葦原涼",
select2: "木野薫",
select3: "津上翔一",
select4: "永川誠",
result_id: 3
},
{ 
content: "（津上翔一より分岐、仮面ライダーアギトで）アナザーアギトに変身するのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "津上翔一",
select2: "永川誠",
select3: "木野薫",
select4: "葦原涼",
result_id: 3
},
{ 
content: "アニメ「極上生徒会」で極上生徒会の会長を務めるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "神宮司奏",
select2: "金城奈々穂",
select3: "市川まゆら",
select4: "銀河久遠",
result_id: 1
},
{ 
content: "次のうち、SCEからPS用シューティングゲームとして発売されたことのあるタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "道頓堀",
select2: "北新地",
select3: "大阪城",
select4: "通天閣",
result_id: 4
},
{ 
content: "小学生ユニット「くろーばー」が歌う、関西テレビのアニメ「うんこさん」の主題歌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "うんとこマンボ",
select2: "うんとこジルバ",
select3: "うんとこサンバ",
select4: "うんとこルンバ",
result_id: 3
},
{ 
content: "メガドライブ用アクションゲーム「ベアナックル」で、シリーズを通して登場するキャラクターはアクセルと誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "サミー",
select2: "アダム",
select3: "マックス",
select4: "ブレイズ",
result_id: 4
},
{ 
content: "手塚治虫の漫画「鉄腕アトム」で天馬博士がアトムを売り飛ばしたのはどこ？",
result: 0,
sum: 0,
user_id: 1,
select1: "サーカス",
select2: "工場",
select3: "お化け屋敷",
select4: "ジャンク屋",
result_id: 1
},
{ 
content: "漫画「家庭教師ヒットマンREBORN」で、リボーンが家庭教師として勉強を教えている少年は？",
result: 0,
sum: 0,
user_id: 1,
select1: "沢田綱吉",
select2: "沢田家光",
select3: "沢田吉宗",
select4: "沢田慶喜",
result_id: 1
},
{ 
content: "バンダイのPS２ゲーム「.hack／／」シリーズ最終作のサブタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "侵食汚染",
select2: "絶対包囲",
select3: "悪性変異",
select4: "感染拡大",
result_id: 2
},
{ 
content: "主人公の岡ひろみが一流テニス選手になるまでを描く漫画「エースをねらえ」の作者は？",
result: 0,
sum: 0,
user_id: 1,
select1: "塀内夏子",
select2: "山本鈴美香",
select3: "羅川真里茂",
select4: "佐伯かよの",
result_id: 2
},
{ 
content: "次のキャラクターのうち日本語を話すことができないのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "スパンク",
select2: "ケンケン",
select3: "ウナギイヌ",
select4: "獅子丸",
result_id: 1
},
{ 
content: "石ノ森章太郎の漫画「仮面ライダー」が連載された漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊少年サンデー",
select2: "週刊少年チャンピオン",
select3: "週刊少年ジャンプ",
select4: "週刊少年マガジン",
result_id: 4
},
{ 
content: "（週刊少年マガジンより分岐）「仮面ライダーBlack」が連載された漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊少年チャンピオン",
select2: "週刊少年サンデー",
select3: "週刊少年ジャンプ",
select4: "週刊少年マガジン",
result_id: 2
},
{ 
content: "TVアニメ「科学忍者隊ガッチャマン」で燕の甚平が使う武器はどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "ヨーヨーの写真",
select2: "カチンカチンの写真",
select3: "コマの写真",
select4: "けん玉の写真",
result_id: 2
},
{ 
content: "任天堂がゲームキューブで発売したアドベンチャーゲーム「エターナルダークネス」のサブタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "招かれた13人",
select2: "招かれた12人",
select3: "招かれた10人",
select4: "招かれた11人",
result_id: 1
},
{ 
content: "アニメ「鋼の錬金術師」に登場するロイ・マスタングが炎を生み出すときに使う道具は？",
result: 0,
sum: 0,
user_id: 1,
select1: "コート",
select2: "帽子",
select3: "手袋",
select4: "ブローチ",
result_id: 3
},
{ 
content: "アニメ「鋼の錬金術師」で「鋼の錬金術師」の二つ名を持つのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "ショウ・タッカー",
select2: "ルイ・アームストロング",
select3: "リザ・ホークアイ",
select4: "エドワード・エルリック",
result_id: 4
},
{ 
content: "（エドワード・エルリックより分岐、鋼の錬金術師で）「綴命の錬金術師」の二つ名を持つのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "エドワード・エルリック",
select2: "ルイ・アームストロング",
select3: "ショウ・タッカー",
select4: "リザ・ホークアイ",
result_id: 3
},
{ 
content: "2009年にフランスの最高勲章「レジオン・ド・ヌール」を受賞した日本の漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "山本鈴美香",
select2: "池田理代子",
select3: "美内すずえ",
select4: "竹宮恵子",
result_id: 2
},
{ 
content: "声優の林原めぐみのシングル「Give a reason」が主題歌に使われたアニメは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ラブひな",
select2: "スレイヤーズNEXT",
select3: "ロストユニバース",
select4: "シャーマンキング",
result_id: 2
},
{ 
content: "（スレイヤーズNEXTより分岐、林原めぐみの）「Over Soul」が主題歌に使われたアニメは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ロストユニバース",
select2: "シャーマンキング",
select3: "スレイヤーズNEXT",
select4: "ラブひな",
result_id: 2
},
{ 
content: "かつて「週刊少年マガジン」誌上で「ウルトラマン」の漫画版を連載した漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ちばてつや",
select2: "あだち充",
select3: "さいとう・たかを",
select4: "楳図かずお",
result_id: 4
},
{ 
content: "2009年8月に発売されたDS用ゲーム「スパロボ学園」のキャラクターデザインを担当したイラストレーターは？",
result: 0,
sum: 0,
user_id: 1,
select1: "天広直人",
select2: "みつみ美里",
select3: "うるし原智志",
select4: "駒都えーじ",
result_id: 4
},
{ 
content: "2004年放送のTVアニメ「レジェンズ　甦る竜王伝説」のエンディングテーマに使われた曲は？",
result: 0,
sum: 0,
user_id: 1,
select1: "山本リンダの「どうにもとまらない」",
select2: "岩崎宏美「聖母たちのララバイ」",
select3: "中島みゆきの「時代」",
select4: "山口百恵「いい日旅立ち」",
result_id: 1
},
{ 
content: "藤田和日郎の漫画「月光条例」に登場する主人公・岩崎月光の幼なじみは何と呼ばれている？",
result: 0,
sum: 0,
user_id: 1,
select1: "新聞部",
select2: "柔道部",
select3: "茶道部",
select4: "演劇部",
result_id: 4
},
{ 
content: "漫画「金色のガッシュ」でガッシュとともに戦うパートナーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "リィエン",
select2: "高嶺清麿",
select3: "大海恵",
select4: "シェリー",
result_id: 2
},
{ 
content: "（高嶺清麿より分岐）フラゴとともに戦うパートナーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "リィエン",
select2: "高嶺清麿",
select3: "シェリー",
select4: "大海恵",
result_id: 3
},
{ 
content: "ファミコンゲーム「夢ペンギン物語」に登場する主人公・ペン太のライバルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ギン次",
select2: "ギン助",
select3: "ギン吉",
select4: "ギン蔵",
result_id: 1
},
{ 
content: "アニメ「犬夜叉」に登場する七人隊の首領は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "蛮骨",
select2: "鉄骨",
select3: "拳骨",
select4: "軟骨",
result_id: 1
},
{ 
content: "ゲーム「コナミのピンポン」を「スマッシュピンポン」というファミコンゲームとして発売したメーカーは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ジャレコ",
select2: "ナムコ",
select3: "タイトー",
select4: "任天堂",
result_id: 4
},
{ 
content: "アニメ「∀ガンダム」で核弾頭の爆発に巻き込まれて死亡した、ボルジャーノン隊の隊長は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "シャリバン",
select2: "ギャバン",
select3: "ジャスピオン",
select4: "シャイダー",
result_id: 2
},
{ 
content: "漫画「ジョジョの奇妙な冒険」第5部で、主人公ジョルノのスタンドは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ムーディー・ブルース",
select2: "セックス・ピストルズ",
select3: "スティッキィ・フィンガーズ",
select4: "ゴールドエクスペリエンス",
result_id: 4
},
{ 
content: "（ゴールド・エクスペリエンスより分岐、ジョジョの奇妙な冒険第5部で）アバッキオのスタンドは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ゴールドエクスペリエンス",
select2: "セックス・ピストルズ",
select3: "ムーディー・ブルース",
select4: "スティッキィ・フィンガーズ",
result_id: 3
},
{ 
content: "国内初のフィギュア専門博物館「海洋堂フィギュアミュージアム黒壁」がオープンした都道府県は？",
result: 0,
sum: 0,
user_id: 1,
select1: "大阪府",
select2: "和歌山県",
select3: "滋賀県",
select4: "京都府",
result_id: 3
},
{ 
content: "（おひさまの国より分岐、ふしぎ星のふたご姫で）ミルロはどこの国のプリンセス？",
result: 0,
sum: 0,
user_id: 1,
select1: "おひさまの国",
select2: "しずくの国",
select3: "月の国",
select4: "メラメラの国",
result_id: 2
},
{ 
content: "「外交」という意味を持つボードゲーム「ディプロマシー」は、いつの時代のどこを題材としている？",
result: 0,
sum: 0,
user_id: 1,
select1: "第二次世界大戦中の太平洋",
select2: "ナポレオン戦争後のヨーロッパ",
select3: "第一次世界大戦前のヨーロッパ",
select4: "冷戦下のアジア",
result_id: 3
},
{ 
content: "2003年放送のTVアニメ「アストロボーイ・鉄腕アトム」で、和登千代子の声を演じた女性タレントは？",
result: 0,
sum: 0,
user_id: 1,
select1: "山田まりや",
select2: "佐藤江梨子",
select3: "MEGUMI",
select4: "小池栄子",
result_id: 3
},
{ 
content: "2010年放送のTVアニメ「閃光のナイトレイド」のキャラクター原案を担当した漫画家は？",
result: 0,
sum: 0,
user_id: 1,
select1: "恵広史",
select2: "中丸洋介",
select3: "上条明峰",
select4: "大暮維人",
result_id: 3
},
{ 
content: "ディスクシステムのゲーム「帰ってきたマリオブラザーズ」のオープニングに流れるのはどこのCM？",
result: 0,
sum: 0,
user_id: 1,
select1: "大塚製薬",
select2: "東ハト",
select3: "コカコーラ",
select4: "永谷園",
result_id: 4
},
{ 
content: "アニメ「トランスフォーマー　マイクロン伝説」で、破壊大帝メガトロンがダブルフェイスに仕掛けたことのある攻撃は？",
result: 0,
sum: 0,
user_id: 1,
select1: "肩固め",
select2: "崩上四方固め",
select3: "送襟絞め",
select4: "腕挫十字固め",
result_id: 4
},
{ 
content: "SMAPが歌ったアニメ「姫ちゃんのリボン」のオープニング曲は？",
result: 0,
sum: 0,
user_id: 1,
select1: "笑顔のゲンキ",
select2: "はじめての夏",
select3: "君色思い",
select4: "ずっと忘れない",
result_id: 1
},
{ 
content: "漫画「めぞん一刻」が実写映画化された時にヒロイン・音無響子を演じたのは誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "石原真理子",
select2: "浅香唯",
select3: "小泉今日子",
select4: "内田有紀",
result_id: 1
},
{ 
content: "（石原真理子より分岐）「花より男子」が実写映画化された時にヒロイン・牧野つくしを演じたのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "小泉今日子",
select2: "内田有紀",
select3: "石原真理子",
select4: "浅香唯",
result_id: 2
},
{ 
content: "漫画「ブラックジャックによろしく」が連載されていた漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ビッグコミックスピリッツ",
select2: "スーパージャンプ",
select3: "週刊モーニング",
select4: "週刊ヤングマガジン",
result_id: 3
},
{ 
content: "（週刊モーニングより分岐）その続編「新ブラックジャックによろしく」が連載されている漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ビッグコミックスピリッツ",
select2: "週刊モーニング",
select3: "スーパージャンプ",
select4: "週刊ヤングマガジン",
result_id: 1
},
{ 
content: "アニメ「るろうに剣心」がアメリカで放送されたときのタイトルは？",
result: 0,
sum: 0,
user_id: 1,
select1: "SAMURA A",
select2: "SAMURAI R",
select3: "SAMURAI X",
select4: "SAMURAI J",
result_id: 3
},
{ 
content: "2010年より「月間チャンピオンRED」に連載されている「永井豪とダイナミックプロ」の漫画は「デビルマン対”何”」？",
result: 0,
sum: 0,
user_id: 1,
select1: "グレートマジンガー",
select2: "ゲッターロボ",
select3: "グレンダイザー",
select4: "マジンガーZ",
result_id: 2
},
{ 
content: "岡田芽武の漫画「聖闘士星矢エピソードQ」の主人公である黄金聖闘士は？",
result: 0,
sum: 0,
user_id: 1,
select1: "牡羊座のムウ",
select2: "獅子座のアイオリア",
select3: "乙女座のシャカ",
select4: "蠍座のミロ",
result_id: 2
},
{ 
content: "2010年に「12人同時オンライン対戦」などのアレンジを加えたリメイク版がPS3で発売されるサン電子のゲームは？",
result: 0,
sum: 0,
user_id: 1,
select1: "東海道五十三次",
select2: "アトランチスの謎",
select3: "スーパーアラビアン",
select4: "いっき",
result_id: 4
},
{ 
content: "1990年に放送されたアニメ「もーれつア太郎」の主題歌を歌ったタレントは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ビートたけし",
select2: "明石家さんま",
select3: "島田紳助",
select4: "タモリ",
result_id: 3
},
{ 
content: "アニメ「おジャ魔女どれみ」で春風どれみの声を演じた声優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "宮原永海",
select2: "松岡由貴",
select3: "千葉千恵巳",
select4: "宍戸留美",
result_id: 3
},
{ 
content: "（千葉千恵巳より分岐、おジャ魔女どれみで）瀬川おんぷの声を演じた声優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "松岡由貴",
select2: "宍戸留美",
select3: "千葉千恵巳",
select4: "宮原永海",
result_id: 2
},
{ 
content: "漫画「銀河鉄道999」が連載されていた漫画雑誌は？",
result: 0,
sum: 0,
user_id: 1,
select1: "週刊少年マガジン",
select2: "週刊少年キング",
select3: "週刊少年チャンピオン",
select4: "週刊少年サンデー",
result_id: 2
},
{ 
content: "2008年公開のアニメ映画「スカイ・クロラ」の原作者は？",
result: 0,
sum: 0,
user_id: 1,
select1: "森博嗣",
select2: "石田衣良",
select3: "神林長平",
select4: "福井晴敏",
result_id: 1
},
{ 
content: "ゲーム「ロックマンDASH」に登場する、3人姉弟と40人のコブンからなる空賊は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ゴーン一家",
select2: "ドーン一家",
select3: "ボーン一家",
select4: "バーン一家",
result_id: 3
},
{ 
content: "ゲーム「スーパーロボット大戦」シリーズのオリジナルロボットで、サイバスターのパイロットは？",
result: 0,
sum: 0,
user_id: 1,
select1: "キョウスケ・ナンブ",
select2: "マサキ・アンドー",
select3: "クスハ・ミズハ",
select4: "リューネ・ゾルダーク",
result_id: 2
},
{ 
content: "（マサキ・アンドーより分岐、ロボット大戦で）ヴァルシオーネRのパイロットは？",
result: 0,
sum: 0,
user_id: 1,
select1: "リューネ・ゾルダーク",
select2: "クスハ・ミズハ",
select3: "キョウスケ・ナンブ",
select4: "マサキ・アンドー",
result_id: 1
},
{ 
content: "阿智太郎のライトノベル「住めば都のコスモス荘」で主人公・桜咲鈴雄が住んでいるのはコスモス荘の何号室？",
result: 0,
sum: 0,
user_id: 1,
select1: "5号室",
select2: "6号室",
select3: "3号室",
select4: "4号室",
result_id: 1
},
{ 
content: "漫画「ドカベン　プロ野球編」で山田太郎が入団したプロ野球球団は？",
result: 0,
sum: 0,
user_id: 1,
select1: "西武ライオンズ",
select2: "千葉ロッテマリーンズ",
select3: "福岡ダイエーホークス",
select4: "日本ハムファイターズ",
result_id: 1
},
{ 
content: "（西武ライオンズより分岐、ドカベンプロ野球編で）岩鬼正美が入団したプロ野球球団は？",
result: 0,
sum: 0,
user_id: 1,
select1: "西武ライオンズ",
select2: "福岡ダイエーホークス",
select3: "日本ハムファイターズ",
select4: "千葉ロッテマリーンズ",
result_id: 2
},
{ 
content: "野球漫画「ドカベン」の主人公・山田太郎のポジションは？",
result: 0,
sum: 0,
user_id: 1,
select1: "三塁手",
select2: "二塁手",
select3: "捕手",
select4: "一塁手",
result_id: 3
},
{ 
content: "（捕手より分岐、ドカベンで）岩鬼正美のポジションは？",
result: 0,
sum: 0,
user_id: 1,
select1: "三塁手",
select2: "二塁手",
select3: "一塁手",
select4: "捕手",
result_id: 1
},
{ 
content: "福田政雄の小説「殿がくる」で現代にタイムスリップしてくる殿様といえば？",
result: 0,
sum: 0,
user_id: 1,
select1: "織田信長",
select2: "豊臣秀吉",
select3: "武田信玄",
select4: "徳川家康",
result_id: 1
},
{ 
content: "アニメ「おジャ魔女どれみ」シリーズに登場する魔女見習いの女の子のうち、元チャイドルなのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "妹尾あいこ",
select2: "飛鳥ももこ",
select3: "藤原はづき",
select4: "瀬川おんぷ",
result_id: 4
},
{ 
content: "小説版「∀ガンダム」を執筆した作家は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "有栖川有栖",
select2: "京極夏彦",
select3: "福井晴敏",
select4: "東直己",
result_id: 3
},
{ 
content: "エドモンド・ハミルトンのSF小説「キャプテン・フューチャー」の主人公キャプテン・フューチャーの本名は？",
result: 0,
sum: 0,
user_id: 1,
select1: "カーティス・ニュートン",
select2: "カーティス・フレミング",
select3: "カーティス・エジソン",
select4: "カーティス・ダーウィン",
result_id: 1
},
{ 
content: "（東京スーパースターズより分岐、ドカベンで）真田一球が入団した球団は？",
result: 0,
sum: 0,
user_id: 1,
select1: "四国アイアンドックス",
select2: "東北楽天ゴールデンイーグルス",
select3: "千葉ロッテマリーンズ",
select4: "東京スーパースターズ",
result_id: 2
},
{ 
content: "アニメ「Fate／stay night」で、主人公・衛宮士郎が契約したサーヴァントは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ランサー",
select2: "ライダー",
select3: "アーチャー",
select4: "セイバー",
result_id: 4
},
{ 
content: "（セイバーより分岐、Fateで）逢坂凛が契約したサーヴァントは？",
result: 0,
sum: 0,
user_id: 1,
select1: "アーチャー",
select2: "ライダー",
select3: "セイバー",
select4: "ランサー",
result_id: 1
},
{ 
content: "2010年放送のTVアニメ「RAINBOW　二舎六房の七人」で主人公・水上真理雄の声を演じる俳優は？",
result: 0,
sum: 0,
user_id: 1,
select1: "生田斗真",
select2: "成宮寛貴",
select3: "小栗旬",
select4: "水嶋ヒロ",
result_id: 3
},
])