Problem.create([ { 
content: "世界的には僅かな面積を占めるに過ぎない、一般にイメージされる砂に覆われた砂漠を指す用語は何？",
result: 0,
sum: 0,
user_id: 1,
select1: "エルグ",
select2: "オルグ",
select3: "ミルグ",
select4: "ユルグ",
result_id: 1
},
{ 
content: "りゅう座にあるこの星雲の名前は？（写真）",
result: 0,
sum: 0,
user_id: 1,
select1: "トパーズ星雲",
select2: "ルビー星雲",
select3: "キャッツアイ星雲",
select4: "アメシスト星雲",
result_id: 3
},
{ 
content: "肥満度を測る指数「BMI」で最も病気になりにくいとされる数値は？",
result: 0,
sum: 0,
user_id: 1,
select1: "20",
select2: "24",
select3: "23",
select4: "22",
result_id: 4
},
{ 
content: "20世紀の初めに日本の小川正孝が発見・命名した幻の元素は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ヤマトニウム",
select2: "トウキョニウム",
select3: "ニッポニウム",
select4: "ジャパニウム",
result_id: 3
},
{ 
content: "次の生物のうち最も染色体の数が多いのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "ネコ",
select2: "ブタ",
select3: "イヌ",
select4: "ウマ",
result_id: 3
},
{ 
content: "相対性理論で知られる物理学者アインシュタインが生まれた国は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ドイツ",
select2: "デンマーク",
select3: "フランス",
select4: "ベルギー",
result_id: 1
},
{ 
content: "血液循環の理論を打ち立てたイギリスの医学者は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "ジェンナー",
select2: "ハーベイ",
select3: "フレミング",
select4: "ウェーラー",
result_id: 2
},
{ 
content: "中央アジアを横断する交易路を「シルクロード」と命名したドイツの地理学者は？",
result: 0,
sum: 0,
user_id: 1,
select1: "ラッツェル",
select2: "リッター",
select3: "フンボルト",
select4: "リヒトホーフェン",
result_id: 4
},
{ 
content: "顕著な業績を上げた数学者に贈られる「アーベル賞」を2003年に初めて受賞したフランスの数学者は誰？",
result: 0,
sum: 0,
user_id: 1,
select1: "ピーター・ラックス",
select2: "ジャン＝ピエール・セール",
select3: "イサドール・シンガー",
select4: "マイケル・アティヤ",
result_id: 2
},
{ 
content: "「ビタミン」という用語を命名したフンクはどこの国出身の化学者？",
result: 0,
sum: 0,
user_id: 1,
select1: "ベルギー",
select2: "ブルガリア",
select3: "スイス",
select4: "ポーランド",
result_id: 4
},
{ 
content: "ゲンゴロウブナやニゴロブナの原産地である湖は？",
result: 0,
sum: 0,
user_id: 1,
select1: "宍道湖",
select2: "琵琶湖",
select3: "霞ヶ浦",
select4: "支笏湖",
result_id: 2
},
{ 
content: "太陽系の惑星で、大赤斑があるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "木星",
select2: "天王星",
select3: "海王星",
select4: "土星",
result_id: 1
},
{ 
content: "（木星より分岐）大黒斑がかつてあったのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "木星",
select2: "天王星",
select3: "海王星",
select4: "土星",
result_id: 3
},
{ 
content: "海辺に分布する植物ハマナスは何科？",
result: 0,
sum: 0,
user_id: 1,
select1: "バラ科",
select2: "セリ科",
select3: "ヒガンバナ科",
select4: "ヒルガオ科",
result_id: 1
},
{ 
content: "（バラ科より分岐）ハマボウフウは何科？",
result: 0,
sum: 0,
user_id: 1,
select1: "バラ科",
select2: "セリ科",
select3: "ヒガンバナ科",
select4: "ヒルガオ科",
result_id: 2
},
{ 
content: "1897年に第1回国際数学者会議が開催された都市はどこ？",
result: 0,
sum: 0,
user_id: 1,
select1: "ベルン",
select2: "チューリヒ",
select3: "ローザンヌ",
select4: "ジュネーブ",
result_id: 2
},
{ 
content: "一般的な予防接種におけるワクチンを大別すると生ワクチン、不活性ワクチンとあと一つは何？",
result: 0,
sum: 0,
user_id: 1,
select1: "サイクロイド",
select2: "トキソイド",
select3: "パラノイド",
select4: "アルカノイド",
result_id: 2
},
{ 
content: "「月食」の際月に影を落とす天体はどれ？",
result: 0,
sum: 0,
user_id: 1,
select1: "金星",
select2: "ブラックホール",
select3: "太陽",
select4: "地球",
result_id: 4
},
{ 
content: "太陽系の惑星のうち唯一自転の方向が他の惑星と異なるのは？",
result: 0,
sum: 0,
user_id: 1,
select1: "金星",
select2: "木星",
select3: "海王星",
select4: "水星",
result_id: 1
},
{ 
content: "ソテツの精子を発見して被子植物とシダ植物の類縁関係を究明した植物学者は？",
result: 0,
sum: 0,
user_id: 1,
select1: "平瀬作五郎",
select2: "池野成一郎",
select3: "牧野富太郎",
select4: "白井光太郎",
result_id: 2
},
])